// packages/ui/src/components/ProgressIndicator/ProgressIndicator.jsx
import React, { forwardRef } from 'react';
import PropTypes from 'prop-types';
import './ProgressIndicator.css';

/* ==========================================================================
   EXPORTED SVG COMPONENTS FOR PROGRESS INDICATORS
   ========================================================================== */

/** Linear Progress Bar SVG Track */
export const LinearProgressBarSvg = ({
  progress = 0,
  type = 'determinate',
  trackColor = 'var(--color-progress-track-inactive, #E3E3E8)',
  fillColor = 'var(--color-progress-track-active, #1E49E2)',
  height = 4,
  ...props
}) => {
  const isIndeterminate = type === 'indeterminate';
  const clampedProgress = Math.min(Math.max(progress, 0), 100);

  return (
    <div
      className={`kpmg-progress__linear-track ${isIndeterminate ? 'kpmg-progress__linear-track--indeterminate' : ''}`}
      style={{ height: `${height}px`, backgroundColor: trackColor }}
      {...props}
    >
      <div
        className={`kpmg-progress__linear-fill ${isIndeterminate ? 'kpmg-progress__linear-fill--indeterminate' : ''}`}
        style={{
          width: isIndeterminate ? '40%' : `${clampedProgress}%`,
          backgroundColor: fillColor,
        }}
      />
    </div>
  );
};

/** Circular Progress Bar SVG Ring */
export const CircularProgressBarSvg = ({
  size = 'large', // 'large' (88px) | 'medium' (48px) | 'small' (24px)
  progress = 0,
  type = 'determinate',
  trackColor = 'var(--color-progress-track-inactive, #E3E3E8)',
  fillColor = 'var(--color-progress-track-active, #1E49E2)',
  showValue = false,
  ...props
}) => {
  const normalizedSize = (size || 'large').toLowerCase();
  let diameter = 88;
  let strokeWidth = 6;

  if (normalizedSize === 'medium') {
    diameter = 48;
    strokeWidth = 4;
  } else if (normalizedSize === 'small') {
    diameter = 24;
    strokeWidth = 2.5;
  }

  const radius = (diameter - strokeWidth) / 2;
  const circumference = 2 * Math.PI * radius;
  const clampedProgress = Math.min(Math.max(progress, 0), 100);
  const strokeDashoffset = circumference - (clampedProgress / 100) * circumference;
  const isIndeterminate = type === 'indeterminate';

  return (
    <div
      className={`kpmg-progress__circular-container kpmg-progress__circular-container--${normalizedSize} ${isIndeterminate ? 'kpmg-progress__circular-container--indeterminate' : ''}`}
      style={{ width: `${diameter}px`, height: `${diameter}px` }}
      {...props}
    >
      <svg
        viewBox={`0 0 ${diameter} ${diameter}`}
        width={diameter}
        height={diameter}
        className={`kpmg-progress__circular-svg ${isIndeterminate ? 'kpmg-progress__circular-svg--indeterminate' : ''}`}
      >
        {/* Background Track Circle */}
        <circle
          cx={diameter / 2}
          cy={diameter / 2}
          r={radius}
          fill="none"
          stroke={trackColor}
          strokeWidth={strokeWidth}
        />
        {/* Progress Fill Arc Circle */}
        <circle
          cx={diameter / 2}
          cy={diameter / 2}
          r={radius}
          fill="none"
          stroke={fillColor}
          strokeWidth={strokeWidth}
          strokeDasharray={circumference}
          strokeDashoffset={isIndeterminate ? circumference * 0.3 : strokeDashoffset}
          strokeLinecap="round"
          className={`kpmg-progress__circular-arc ${isIndeterminate ? 'kpmg-progress__circular-arc--indeterminate' : ''}`}
        />
      </svg>

      {/* Center Value Percentage Text (Large & Medium sizes) */}
      {showValue && !isIndeterminate && normalizedSize !== 'small' && (
        <span className="kpmg-progress__circular-value">{Math.round(clampedProgress)}%</span>
      )}
    </div>
  );
};

/* ==========================================================================
   MAIN PROGRESS INDICATOR COMPONENT (33 FIGMA VARIANTS SUPPORT)
   ========================================================================== */

/**
 * ProgressIndicator Component - KPMG WorkBench Design System
 * Formatted directly to Figma Specs (Node 964:63787).
 * Supports Linear & Circular modes, Determinate & Indeterminate progress types,
 * 33 exact Figma variant combinations, labels, percentage text, and token-driven styles.
 */
export const ProgressIndicator = forwardRef(({
  variant = 'linear', // 'linear' | 'circular'
  type = 'determinate', // 'determinate' | 'indeterminate'
  progress = 0, // 0 to 100
  size = 'large', // 'large' | 'medium' | 'small'
  step, // Step 1..5 for indeterminate
  showValue = false,
  label,
  subtext,
  className = '',
  id,
  'aria-label': ariaLabel,
  ...props
}, ref) => {
  const isLinear = variant === 'linear' || variant === 'Linear';
  const isIndeterminate = type === 'indeterminate' || type === 'Indeterminate';
  const clampedProgress = Math.min(Math.max(progress, 0), 100);
  const normalizedSize = (size || 'large').toLowerCase();

  const containerClasses = [
    'kpmg-progress',
    `kpmg-progress--${isLinear ? 'linear' : 'circular'}`,
    `kpmg-progress--${isIndeterminate ? 'indeterminate' : 'determinate'}`,
    `kpmg-progress--size-${normalizedSize}`,
    className,
  ].filter(Boolean).join(' ');

  return (
    <div
      className={containerClasses}
      ref={ref}
      id={id}
      role="progressbar"
      aria-valuenow={isIndeterminate ? undefined : Math.round(clampedProgress)}
      aria-valuemin={0}
      aria-valuemax={100}
      aria-label={ariaLabel || (typeof label === 'string' ? label : `${variant} progress indicator`)}
      {...props}
    >
      {/* Optional Header (Label & Progress Percentage) */}
      {(label || showValue) && isLinear && (
        <div className="kpmg-progress__header">
          {label && <span className="kpmg-progress__label">{label}</span>}
          {showValue && !isIndeterminate && (
            <span className="kpmg-progress__value-text">{Math.round(clampedProgress)}%</span>
          )}
        </div>
      )}

      {/* Main Visual Progress Render */}
      {isLinear ? (
        <LinearProgressBarSvg
          progress={clampedProgress}
          type={isIndeterminate ? 'indeterminate' : 'determinate'}
        />
      ) : (
        <div className="kpmg-progress__circular-wrapper">
          <CircularProgressBarSvg
            size={normalizedSize}
            progress={clampedProgress}
            type={isIndeterminate ? 'indeterminate' : 'determinate'}
            showValue={showValue}
          />
          {(label || subtext) && (
            <div className="kpmg-progress__circular-labels">
              {label && <span className="kpmg-progress__label">{label}</span>}
              {subtext && <span className="kpmg-progress__subtext">{subtext}</span>}
            </div>
          )}
        </div>
      )}

      {/* Optional Subtext for Linear Bar */}
      {subtext && isLinear && (
        <span className="kpmg-progress__subtext">{subtext}</span>
      )}
    </div>
  );
});

ProgressIndicator.displayName = 'ProgressIndicator';

ProgressIndicator.propTypes = {
  /** Progress indicator variant ('linear' or 'circular') */
  variant: PropTypes.oneOf(['linear', 'circular', 'Linear', 'Circular']),
  /** Progress type ('determinate' for fixed %, 'indeterminate' for loading loop) */
  type: PropTypes.oneOf(['determinate', 'indeterminate', 'Determinate', 'Indeterminate']),
  /** Progress percentage value (0 to 100) */
  progress: PropTypes.number,
  /** Size scale ('large', 'medium', 'small') */
  size: PropTypes.oneOf(['large', 'medium', 'small', 'Large', 'Medium', 'Small']),
  /** Indeterminate step property (Step 1..5 in Figma) */
  step: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
  /** Display value percentage text */
  showValue: PropTypes.bool,
  /** Optional label text or Node */
  label: PropTypes.node,
  /** Optional subtext / description */
  subtext: PropTypes.node,
  /** Custom CSS class name */
  className: PropTypes.string,
  /** HTML element id */
  id: PropTypes.string,
  /** Accessible ARIA label */
  'aria-label': PropTypes.string,
};

export default ProgressIndicator;

// packages/angular/src/lib/progress-indicator/progress-indicator.component.ts
import { ChangeDetectionStrategy, Component, computed, input, booleanAttribute } from '@angular/core';

export type ProgressVariant = 'linear' | 'circular';
export type ProgressType = 'determinate' | 'indeterminate';
export type ProgressSize = 'large' | 'medium' | 'small';

const TRACK = 'var(--color-progress-track-inactive, #E3E3E8)';
const FILL = 'var(--color-progress-track-active, #1E49E2)';

/**
 * WorkBench ProgressIndicator — mirrors
 * packages/ui/src/components/ProgressIndicator/ProgressIndicator.jsx
 * (linear + circular, determinate + indeterminate).
 */
@Component({
  selector: 'kpmg-progress-indicator',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    <div
      [class]="classes()"
      [attr.id]="progressId()"
      role="progressbar"
      [attr.aria-valuenow]="isIndeterminate() ? null : rounded()"
      aria-valuemin="0"
      aria-valuemax="100"
      [attr.aria-label]="computedAriaLabel()"
    >
      @if ((label() || showValue()) && isLinear()) {
        <div class="kpmg-progress__header">
          @if (label()) { <span class="kpmg-progress__label">{{ label() }}</span> }
          @if (showValue() && !isIndeterminate()) { <span class="kpmg-progress__value-text">{{ rounded() }}%</span> }
        </div>
      }
      @if (isLinear()) {
        <div
          [class]="'kpmg-progress__linear-track' + (isIndeterminate() ? ' kpmg-progress__linear-track--indeterminate' : '')"
          style="height: 4px"
          [style.background-color]="track"
        >
          <div
            [class]="'kpmg-progress__linear-fill' + (isIndeterminate() ? ' kpmg-progress__linear-fill--indeterminate' : '')"
            [style.width]="isIndeterminate() ? '40%' : clamped() + '%'"
            [style.background-color]="fill"
          ></div>
        </div>
      } @else {
        <div class="kpmg-progress__circular-wrapper">
          <div
            [class]="'kpmg-progress__circular-container kpmg-progress__circular-container--' + sizeNorm() + (isIndeterminate() ? ' kpmg-progress__circular-container--indeterminate' : '')"
            [style.width.px]="geometry().diameter"
            [style.height.px]="geometry().diameter"
          >
            <svg
              [attr.viewBox]="'0 0 ' + geometry().diameter + ' ' + geometry().diameter"
              [attr.width]="geometry().diameter"
              [attr.height]="geometry().diameter"
              [class]="'kpmg-progress__circular-svg' + (isIndeterminate() ? ' kpmg-progress__circular-svg--indeterminate' : '')"
            >
              <circle [attr.cx]="geometry().diameter / 2" [attr.cy]="geometry().diameter / 2" [attr.r]="geometry().radius" fill="none" [attr.stroke]="track" [attr.stroke-width]="geometry().strokeWidth" />
              <circle
                [attr.cx]="geometry().diameter / 2"
                [attr.cy]="geometry().diameter / 2"
                [attr.r]="geometry().radius"
                fill="none"
                [attr.stroke]="fill"
                [attr.stroke-width]="geometry().strokeWidth"
                [attr.stroke-dasharray]="geometry().circumference"
                [attr.stroke-dashoffset]="dashOffset()"
                stroke-linecap="round"
                [class]="'kpmg-progress__circular-arc' + (isIndeterminate() ? ' kpmg-progress__circular-arc--indeterminate' : '')"
              />
            </svg>
            @if (showValue() && !isIndeterminate() && sizeNorm() !== 'small') {
              <span class="kpmg-progress__circular-value">{{ rounded() }}%</span>
            }
          </div>
          @if (label() || subtext()) {
            <div class="kpmg-progress__circular-labels">
              @if (label()) { <span class="kpmg-progress__label">{{ label() }}</span> }
              @if (subtext()) { <span class="kpmg-progress__subtext">{{ subtext() }}</span> }
            </div>
          }
        </div>
      }
      @if (subtext() && isLinear()) {
        <span class="kpmg-progress__subtext">{{ subtext() }}</span>
      }
    </div>
  `,
})
export class ProgressIndicatorComponent {
  readonly variant = input<ProgressVariant | string>('linear');
  readonly type = input<ProgressType | string>('determinate');
  /** 0–100. */
  readonly progress = input(0);
  readonly size = input<ProgressSize | string>('large');
  readonly showValue = input(false, { transform: booleanAttribute });
  readonly label = input<string | undefined>(undefined);
  readonly subtext = input<string | undefined>(undefined);
  readonly progressId = input<string | undefined>(undefined);
  readonly ariaLabel = input<string | undefined>(undefined);
  readonly className = input('');

  protected readonly track = TRACK;
  protected readonly fill = FILL;

  protected readonly isLinear = computed(() => this.variant().toLowerCase() === 'linear');
  protected readonly isIndeterminate = computed(() => this.type().toLowerCase() === 'indeterminate');
  protected readonly clamped = computed(() => Math.min(Math.max(this.progress(), 0), 100));
  protected readonly rounded = computed(() => Math.round(this.clamped()));
  protected readonly sizeNorm = computed(() => (this.size() || 'large').toLowerCase());

  protected readonly geometry = computed(() => {
    const size = this.sizeNorm();
    const diameter = size === 'medium' ? 48 : size === 'small' ? 24 : 88;
    const strokeWidth = size === 'medium' ? 4 : size === 'small' ? 2.5 : 6;
    const radius = (diameter - strokeWidth) / 2;
    return { diameter, strokeWidth, radius, circumference: 2 * Math.PI * radius };
  });

  protected readonly dashOffset = computed(() => {
    const { circumference } = this.geometry();
    return this.isIndeterminate() ? circumference * 0.3 : circumference - (this.clamped() / 100) * circumference;
  });

  protected readonly computedAriaLabel = computed(
    () => this.ariaLabel() || this.label() || `${this.variant()} progress indicator`,
  );

  protected readonly classes = computed(() =>
    [
      'kpmg-progress',
      `kpmg-progress--${this.isLinear() ? 'linear' : 'circular'}`,
      `kpmg-progress--${this.isIndeterminate() ? 'indeterminate' : 'determinate'}`,
      `kpmg-progress--size-${this.sizeNorm()}`,
      this.className(),
    ]
      .filter(Boolean)
      .join(' '),
  );
}
