// packages/ui/src/components/Slider/Slider.jsx
import React, { forwardRef, useState, useEffect } from 'react';
import PropTypes from 'prop-types';
import './Slider.css';

/* ==========================================================================
   EXPORTED SVG COMPONENTS FOR SLIDER
   ========================================================================== */

/** Default Circle Thumb Handle SVG */
export const SliderThumbIconSvg = ({
  size = 16,
  fill = 'var(--color-slider-thumb-fill, #1E49E2)',
  ...props
}) => (
  <svg viewBox="0 0 24 24" width={size} height={size} fill="none" aria-hidden="true" {...props}>
    <circle cx="12" cy="12" r="10" fill={fill} />
  </svg>
);

/** Tooltip Value Indicator Badge SVG Pointer */
export const SliderIndicatorBadgeSvg = ({
  value,
  children,
  ...props
}) => (
  <div className="kpmg-slider__indicator-badge" {...props}>
    <span className="kpmg-slider__indicator-text">{children !== undefined ? children : value}</span>
    <span className="kpmg-slider__indicator-arrow" aria-hidden="true" />
  </div>
);

/* ==========================================================================
   MAIN SLIDER COMPONENT (CONTINUOUS & DISCRETE + 15 FIGMA VARIANTS)
   ========================================================================== */

/**
 * Slider Component - KPMG WorkBench Design System
 * Formatted directly to Figma Specs (Node 964:63925).
 * Supports Continuous & Discrete modes, 15 core variant states,
 * Tooltip value indicator badges, step tick marks, and custom SVG props.
 */
export const Slider = forwardRef(({
  variant = 'continuous', // 'continuous' | 'discrete'
  value: controlledValue,
  defaultValue = 50,
  min = 0,
  max = 100,
  step,
  state = 'enabled', // 'enabled' | 'disabled' | 'hovered' | 'pressed'
  showIndicator = false, // Floating tooltip value indicator badge above thumb
  showTicks, // Auto-enabled for discrete, or explicit boolean
  disabled = false,
  label,
  subtext,
  thumbIcon: customThumbIcon,
  indicatorIcon: customIndicatorIcon,
  onChange,
  className = '',
  id,
  name,
  'aria-label': ariaLabel,
  ...props
}, ref) => {
  // Determine if discrete variant
  const isDiscrete = variant === 'discrete';
  const defaultStep = isDiscrete ? 10 : 1;
  const activeStep = step !== undefined ? step : defaultStep;

  // Manage internal value state if uncontrolled
  const [internalValue, setInternalValue] = useState(
    controlledValue !== undefined ? controlledValue : defaultValue
  );

  useEffect(() => {
    if (controlledValue !== undefined) {
      setInternalValue(controlledValue);
    }
  }, [controlledValue]);

  // Compute active normalized value and percentage
  const currentValue = controlledValue !== undefined ? controlledValue : internalValue;
  const clampedValue = Math.min(Math.max(currentValue, min), max);
  const percentage = max > min ? ((clampedValue - min) / (max - min)) * 100 : 0;

  // Determine state
  const isComponentDisabled = disabled || state === 'disabled' || state === 'Disabled';
  const normalizedState = isComponentDisabled ? 'disabled' : (state || 'enabled').toLowerCase();
  const shouldShowIndicator = showIndicator || state === 'Enabled with indicator' || state === 'enabled_with_indicator';
  const shouldShowTicks = showTicks !== undefined ? showTicks : isDiscrete;

  // Generate discrete tick marks
  const tickPositions = [];
  if (shouldShowTicks && max > min && activeStep > 0) {
    const totalSteps = Math.floor((max - min) / activeStep);
    for (let i = 0; i <= totalSteps; i++) {
      const stepVal = min + i * activeStep;
      const stepPercent = ((stepVal - min) / (max - min)) * 100;
      tickPositions.push({ value: stepVal, percent: stepPercent });
    }
  }

  // Handle native slider change
  const handleChange = (e) => {
    const val = Number(e.target.value);
    if (controlledValue === undefined) {
      setInternalValue(val);
    }
    if (onChange) {
      onChange(e, val);
    }
  };

  const containerClasses = [
    'kpmg-slider',
    `kpmg-slider--${variant}`,
    `kpmg-slider--state-${normalizedState}`,
    isComponentDisabled ? 'kpmg-slider--disabled' : '',
    shouldShowIndicator ? 'kpmg-slider--has-indicator' : '',
    className,
  ].filter(Boolean).join(' ');

  return (
    <div className={containerClasses}>
      {/* Optional Label Header */}
      {(label || subtext) && (
        <div className="kpmg-slider__header">
          {label && <span className="kpmg-slider__label">{label}</span>}
          {subtext && <span className="kpmg-slider__subtext">{subtext}</span>}
        </div>
      )}

      {/* Main Track & Thumb Container */}
      <div className="kpmg-slider__wrapper">
        {/* Inactive Background Track */}
        <div className="kpmg-slider__track-bg">
          {/* Active Progress Track Fill */}
          <div
            className="kpmg-slider__track-fill"
            style={{ width: `${percentage}%` }}
          />

          {/* Discrete Step Tick Dots */}
          {shouldShowTicks && tickPositions.length > 0 && (
            <div className="kpmg-slider__ticks" aria-hidden="true">
              {tickPositions.map((tick) => (
                <span
                  key={tick.value}
                  className={`kpmg-slider__tick ${tick.percent <= percentage ? 'kpmg-slider__tick--active' : ''}`}
                  style={{ left: `${tick.percent}%` }}
                />
              ))}
            </div>
          )}
        </div>

        {/* Floating Tooltip Indicator Badge above Thumb */}
        {shouldShowIndicator && (
          <div
            className="kpmg-slider__indicator-container"
            style={{ left: `${percentage}%` }}
          >
            {customIndicatorIcon ? (
              customIndicatorIcon
            ) : (
              <SliderIndicatorBadgeSvg value={Math.round(clampedValue)} />
            )}
          </div>
        )}

        {/* Visual Thumb Circle / Focus Halo Container */}
        <div
          className="kpmg-slider__thumb"
          style={{ left: `${percentage}%` }}
          aria-hidden="true"
        >
          {customThumbIcon ? (
            customThumbIcon
          ) : (
            <SliderThumbIconSvg
              size={normalizedState === 'pressed' || normalizedState === 'hovered' ? 22 : 16}
              fill={isComponentDisabled ? 'var(--color-slider-disabled-thumb, #9090A2)' : 'var(--color-slider-thumb-fill, #1E49E2)'}
            />
          )}
        </div>

        {/* Hidden Accessible Native Range Input */}
        <input
          type="range"
          ref={ref}
          id={id}
          name={name}
          min={min}
          max={max}
          step={activeStep}
          value={clampedValue}
          disabled={isComponentDisabled}
          onChange={handleChange}
          aria-label={ariaLabel || (typeof label === 'string' ? label : 'Slider')}
          aria-valuenow={clampedValue}
          aria-valuemin={min}
          aria-valuemax={max}
          className="kpmg-slider__input"
          {...props}
        />
      </div>
    </div>
  );
});

Slider.displayName = 'Slider';

Slider.propTypes = {
  /** Slider variant mode ('continuous' or 'discrete') */
  variant: PropTypes.oneOf(['continuous', 'discrete']),
  /** Controlled slider value (number 0-100) */
  value: PropTypes.number,
  /** Default uncontrolled initial value */
  defaultValue: PropTypes.number,
  /** Minimum slider value */
  min: PropTypes.number,
  /** Maximum slider value */
  max: PropTypes.number,
  /** Step increment value */
  step: PropTypes.number,
  /** Explicit Figma interactive state */
  state: PropTypes.oneOf(['enabled', 'disabled', 'hovered', 'pressed', 'Enabled with indicator', 'Enabled', 'Disabled', 'Hovered', 'Pressed']),
  /** Display floating value badge above thumb */
  showIndicator: PropTypes.bool,
  /** Display discrete step tick marks */
  showTicks: PropTypes.bool,
  /** Disabled state flag */
  disabled: PropTypes.bool,
  /** Optional label text or Node */
  label: PropTypes.node,
  /** Optional subtext / description */
  subtext: PropTypes.node,
  /** Custom SVG Icon to override thumb handle */
  thumbIcon: PropTypes.node,
  /** Custom SVG / Node to override indicator badge */
  indicatorIcon: PropTypes.node,
  /** Change callback handler `(event, value) => {}` */
  onChange: PropTypes.func,
  /** Custom CSS class name */
  className: PropTypes.string,
  /** HTML input id */
  id: PropTypes.string,
  /** HTML input name */
  name: PropTypes.string,
  /** Accessible ARIA label */
  'aria-label': PropTypes.string,
};

export default Slider;

// packages/angular/src/lib/slider/slider.component.ts
import { booleanAttribute, ChangeDetectionStrategy, Component, computed, input, linkedSignal, model, output, TemplateRef } from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';

export type SliderVariant = 'continuous' | 'discrete';
export type SliderState =
  | 'enabled'
  | 'disabled'
  | 'hovered'
  | 'pressed'
  | 'Enabled with indicator'
  | 'enabled_with_indicator'
  | 'Enabled'
  | 'Disabled'
  | 'Hovered'
  | 'Pressed';

export interface SliderChangeEvent {
  event: Event;
  value: number;
}

/** Default circle thumb handle (React: `SliderThumbIconSvg`). */
@Component({
  selector: 'kpmg-slider-thumb-icon',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    <svg viewBox="0 0 24 24" [attr.width]="size()" [attr.height]="size()" fill="none" aria-hidden="true">
      <circle cx="12" cy="12" r="10" [attr.fill]="fill()" />
    </svg>
  `,
})
export class SliderThumbIconComponent {
  readonly size = input(16);
  readonly fill = input('var(--color-slider-thumb-fill, #1E49E2)');
}

/** Tooltip value indicator badge (React: `SliderIndicatorBadgeSvg`). Projected content overrides `value`. */
@Component({
  selector: 'kpmg-slider-indicator-badge',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    <div class="kpmg-slider__indicator-badge">
      <span class="kpmg-slider__indicator-text">{{ value() }}<ng-content /></span>
      <span class="kpmg-slider__indicator-arrow" aria-hidden="true"></span>
    </div>
  `,
})
export class SliderIndicatorBadgeComponent {
  readonly value = input<number | string | undefined>(undefined);
}

/**
 * WorkBench Slider — mirrors packages/ui/src/components/Slider/Slider.jsx.
 * `value` is a model: bind `[(value)]`, or use `defaultValue` for uncontrolled usage.
 *
 * Deviations: `label`/`subtext` are strings (React: ReactNode); `thumbIcon` /
 * `indicatorIcon` are `<ng-template>` references; the React `onChange(e, value)`
 * callback is the `sliderChange` output ({ event, value }); the input id is
 * `sliderId` (so it isn't duplicated on the host); the "Enabled with indicator"
 * state maps to the `enabled` state class (React produced an invalid class name).
 */
@Component({
  selector: 'kpmg-slider',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgTemplateOutlet, SliderThumbIconComponent, SliderIndicatorBadgeComponent],
  host: { style: 'display: contents' },
  template: `
    <div [class]="containerClasses()">
      @if (label() || subtext()) {
        <div class="kpmg-slider__header">
          @if (label()) { <span class="kpmg-slider__label">{{ label() }}</span> }
          @if (subtext()) { <span class="kpmg-slider__subtext">{{ subtext() }}</span> }
        </div>
      }
      <div class="kpmg-slider__wrapper">
        <div class="kpmg-slider__track-bg">
          <div class="kpmg-slider__track-fill" [style.width.%]="percentage()"></div>
          @if (shouldShowTicks() && tickPositions().length > 0) {
            <div class="kpmg-slider__ticks" aria-hidden="true">
              @for (tick of tickPositions(); track tick.value) {
                <span [class]="'kpmg-slider__tick' + (tick.percent <= percentage() ? ' kpmg-slider__tick--active' : '')" [style.left.%]="tick.percent"></span>
              }
            </div>
          }
        </div>

        @if (shouldShowIndicator()) {
          <div class="kpmg-slider__indicator-container" [style.left.%]="percentage()">
            @if (indicatorIcon(); as tpl) {
              <ng-container [ngTemplateOutlet]="tpl" />
            } @else {
              <kpmg-slider-indicator-badge [value]="roundedValue()" />
            }
          </div>
        }

        <div class="kpmg-slider__thumb" [style.left.%]="percentage()" aria-hidden="true">
          @if (thumbIcon(); as tpl) {
            <ng-container [ngTemplateOutlet]="tpl" />
          } @else {
            <kpmg-slider-thumb-icon [size]="thumbSize()" [fill]="thumbFill()" />
          }
        </div>

        <input
          type="range"
          class="kpmg-slider__input"
          [attr.id]="sliderId()"
          [attr.name]="name()"
          [min]="min()"
          [max]="max()"
          [step]="activeStep()"
          [value]="clampedValue()"
          [disabled]="isDisabled()"
          [attr.aria-label]="ariaLabel() || label() || 'Slider'"
          [attr.aria-valuenow]="clampedValue()"
          [attr.aria-valuemin]="min()"
          [attr.aria-valuemax]="max()"
          (input)="onInput($event)"
        />
      </div>
    </div>
  `,
})
export class SliderComponent {
  readonly variant = input<SliderVariant>('continuous');
  /** Current value. Two-way bindable: `[(value)]`. */
  readonly value = model<number | undefined>(undefined);
  /** Initial value when `value` is not bound. */
  readonly defaultValue = input(50);
  readonly min = input(0);
  readonly max = input(100);
  /** Step increment (default 1 continuous, 10 discrete). */
  readonly step = input<number | undefined>(undefined);
  readonly state = input<SliderState>('enabled');
  /** Floating value badge above the thumb. */
  readonly showIndicator = input(false, { transform: booleanAttribute });
  /** Step tick marks; auto-enabled for the discrete variant unless set explicitly. */
  readonly showTicks = input<boolean | undefined>(undefined);
  readonly disabled = input(false, { transform: booleanAttribute });
  readonly label = input<string | undefined>(undefined);
  readonly subtext = input<string | undefined>(undefined);
  readonly thumbIcon = input<TemplateRef<unknown> | null>(null);
  readonly indicatorIcon = input<TemplateRef<unknown> | null>(null);
  readonly className = input('');
  /** Native range input id (named `sliderId` so it isn't duplicated on the host element). */
  readonly sliderId = input<string | undefined>(undefined);
  readonly name = input<string | undefined>(undefined);
  readonly ariaLabel = input<string | undefined>(undefined);

  /** Fires on every user change (React: `onChange(e, value)`). */
  readonly sliderChange = output<SliderChangeEvent>();

  private readonly current = linkedSignal(() => this.value() ?? this.defaultValue());

  protected readonly isDiscrete = computed(() => this.variant() === 'discrete');
  protected readonly activeStep = computed(() => this.step() ?? (this.isDiscrete() ? 10 : 1));
  protected readonly clampedValue = computed(() => Math.min(Math.max(this.current(), this.min()), this.max()));
  protected readonly roundedValue = computed(() => Math.round(this.clampedValue()));
  protected readonly percentage = computed(() =>
    this.max() > this.min() ? ((this.clampedValue() - this.min()) / (this.max() - this.min())) * 100 : 0,
  );

  protected readonly isDisabled = computed(() => this.disabled() || this.state() === 'disabled' || this.state() === 'Disabled');
  protected readonly normalizedState = computed(() => {
    if (this.isDisabled()) return 'disabled';
    const s = (this.state() || 'enabled').toLowerCase();
    return s === 'enabled with indicator' || s === 'enabled_with_indicator' ? 'enabled' : s;
  });
  protected readonly shouldShowIndicator = computed(
    () => this.showIndicator() || this.state() === 'Enabled with indicator' || this.state() === 'enabled_with_indicator',
  );
  protected readonly shouldShowTicks = computed(() => this.showTicks() ?? this.isDiscrete());

  protected readonly tickPositions = computed(() => {
    const ticks: { value: number; percent: number }[] = [];
    const min = this.min();
    const max = this.max();
    const step = this.activeStep();
    if (this.shouldShowTicks() && max > min && step > 0) {
      const totalSteps = Math.floor((max - min) / step);
      for (let i = 0; i <= totalSteps; i++) {
        const v = min + i * step;
        ticks.push({ value: v, percent: ((v - min) / (max - min)) * 100 });
      }
    }
    return ticks;
  });

  protected readonly thumbSize = computed(() => (this.normalizedState() === 'pressed' || this.normalizedState() === 'hovered' ? 22 : 16));
  protected readonly thumbFill = computed(() =>
    this.isDisabled() ? 'var(--color-slider-disabled-thumb, #9090A2)' : 'var(--color-slider-thumb-fill, #1E49E2)',
  );

  protected readonly containerClasses = computed(() =>
    [
      'kpmg-slider',
      `kpmg-slider--${this.variant()}`,
      `kpmg-slider--state-${this.normalizedState()}`,
      this.isDisabled() ? 'kpmg-slider--disabled' : '',
      this.shouldShowIndicator() ? 'kpmg-slider--has-indicator' : '',
      this.className(),
    ]
      .filter(Boolean)
      .join(' '),
  );

  protected onInput(event: Event): void {
    const val = Number((event.target as HTMLInputElement).value);
    this.current.set(val);
    this.value.set(val);
    this.sliderChange.emit({ event, value: val });
  }
}
