// packages/angular/src/lib/button/button.component.ts
import { booleanAttribute, ChangeDetectionStrategy, Component, computed, input, TemplateRef } from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';

export type ButtonVariant = 'primary' | 'tonal' | 'secondary' | 'outline' | 'text' | 'elevated';
export type ButtonSize = 'sm' | 'md' | 'lg';
export type ButtonType = 'button' | 'submit' | 'reset';

/** WorkBench Button — mirrors packages/ui/src/components/Button/Button.jsx. */
@Component({
  selector: 'kpmg-button',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgTemplateOutlet],
  host: { style: 'display: contents' },
  template: `
    <button [class]="classes()" [type]="type()" [disabled]="disabled()">
      @if (leadingIcon(); as icon) {
        <span class="kpmg-button__icon kpmg-button__icon--left" aria-hidden="true">
          <ng-container [ngTemplateOutlet]="icon" />
        </span>
      }
      <span class="kpmg-button__label"><ng-content /></span>
      @if (iconRight(); as icon) {
        <span class="kpmg-button__icon kpmg-button__icon--right" aria-hidden="true">
          <ng-container [ngTemplateOutlet]="icon" />
        </span>
      }
    </button>
  `,
})
export class ButtonComponent {
  readonly variant = input<ButtonVariant>('primary');
  readonly size = input<ButtonSize>('md');
  readonly disabled = input(false, { transform: booleanAttribute });
  /** Full width block modifier. */
  readonly fullWidth = input(false, { transform: booleanAttribute });
  /** Icon rendered before the label, passed as an `<ng-template>` reference. */
  readonly iconLeft = input<TemplateRef<unknown> | null>(null);
  /** Shorthand for `iconLeft`. */
  readonly icon = input<TemplateRef<unknown> | null>(null);
  /** Icon rendered after the label. */
  readonly iconRight = input<TemplateRef<unknown> | null>(null);
  readonly type = input<ButtonType>('button');
  /** Additional CSS class names. */
  readonly className = input('');

  protected readonly leadingIcon = computed(() => this.iconLeft() ?? this.icon());

  protected readonly classes = computed(() =>
    [
      'kpmg-button',
      `kpmg-button--${this.variant()}`,
      `kpmg-button--${this.size()}`,
      this.fullWidth() ? 'kpmg-button--full-width' : '',
      this.className(),
    ]
      .filter(Boolean)
      .join(' '),
  );
}

// packages/ui/src/components/Button/Button.jsx
import React from 'react';
import PropTypes from 'prop-types';
import './Button.css';

/**
 * Primary Button reference component for KPMG WorkBench Design System.
 * Fully aligned with Figma design tokens and component set specifications.
 */
export const Button = ({
  children = 'Button',
  variant = 'primary',
  size = 'md',
  disabled = false,
  fullWidth = false,
  iconLeft = null,
  iconRight = null,
  icon = null,
  onClick,
  type = 'button',
  className = '',
  ...props
}) => {
  // Support both 'iconLeft' or shorthand 'icon'
  const leadingIcon = iconLeft || icon;

  const variantClass = `kpmg-button--${variant}`;
  const sizeClass = `kpmg-button--${size}`;
  const fullWidthClass = fullWidth ? 'kpmg-button--full-width' : '';

  return (
    <button
      type={type}
      disabled={disabled}
      onClick={onClick}
      className={['kpmg-button', variantClass, sizeClass, fullWidthClass, className]
        .filter(Boolean)
        .join(' ')}
      {...props}
    >
      {leadingIcon && (
        <span className="kpmg-button__icon kpmg-button__icon--left" aria-hidden="true">
          {leadingIcon}
        </span>
      )}
      {children && <span className="kpmg-button__label">{children}</span>}
      {iconRight && (
        <span className="kpmg-button__icon kpmg-button__icon--right" aria-hidden="true">
          {iconRight}
        </span>
      )}
    </button>
  );
};

Button.propTypes = {
  /** Button contents or label */
  children: PropTypes.node,
  /** Visual variant style matching Figma component set */
  variant: PropTypes.oneOf(['primary', 'tonal', 'secondary', 'outline', 'text', 'elevated']),
  /** Scale sizing matching Figma component set */
  size: PropTypes.oneOf(['sm', 'md', 'lg']),
  /** Disabled state */
  disabled: PropTypes.bool,
  /** Full width block modifier */
  fullWidth: PropTypes.bool,
  /** Optional icon (SVG element or component) rendered before text */
  iconLeft: PropTypes.node,
  /** Optional icon (SVG element or component) rendered after text */
  iconRight: PropTypes.node,
  /** Shorthand for iconLeft */
  icon: PropTypes.node,
  /** Optional click handler */
  onClick: PropTypes.func,
  /** HTML button type attribute */
  type: PropTypes.oneOf(['button', 'submit', 'reset']),
  /** Additional custom CSS class names */
  className: PropTypes.string,
};

export default Button;
