// packages/ui/src/components/Checkbox/Checkbox.jsx
import React, { forwardRef } from 'react';
import PropTypes from 'prop-types';
import './Checkbox.css';

/* ==========================================================================
   EXPORTED SVG ICONS FOR ALL CHECKBOX VARIANTS
   ========================================================================== */

/** 1. Checked (Solid Fill Circle + Inner Checkmark Tick) */
export const CheckboxCheckedIconSvg = ({
  size = 24,
  fill = 'var(--color-checkbox-primary-fill, #3D405B)',
  tickColor = 'var(--color-checkbox-primary-tick, #FFFFFF)',
  ...props
}) => (
  <svg viewBox="0 0 24 24" width={size} height={size} fill="none" aria-hidden="true" {...props}>
    <circle cx="12" cy="12" r="10" fill={fill} />
    <polyline points="8 12 11 15 16 9" fill="none" stroke={tickColor} strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
  </svg>
);

/** 2. Unchecked Light (Outline Circle + Inner Checkmark Tick) */
export const CheckboxUncheckedLightIconSvg = ({
  size = 24,
  stroke = 'var(--color-checkbox-primary-stroke, #3D405B)',
  ...props
}) => (
  <svg viewBox="0 0 24 24" width={size} height={size} fill="none" aria-hidden="true" {...props}>
    <circle cx="12" cy="12" r="9" stroke={stroke} strokeWidth="2" />
    <polyline points="8 12 11 15 16 9" fill="none" stroke={stroke} strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
  </svg>
);

/** 3. Indeterminate (Outline Circle + Horizontal Minus Dash) */
export const CheckboxIndeterminateIconSvg = ({
  size = 20,
  stroke = 'var(--color-checkbox-primary-stroke, #3D405B)',
  ...props
}) => (
  <svg viewBox="0 0 24 24" width={size} height={size} fill="none" aria-hidden="true" {...props}>
    <circle cx="12" cy="12" r="9" stroke={stroke} strokeWidth="2" />
    <line x1="7" y1="12" x2="17" y2="12" stroke={stroke} strokeWidth="2.5" strokeLinecap="round" />
  </svg>
);

/** 4. Unchecked (Empty Outline Circle) */
export const CheckboxUncheckedIconSvg = ({
  size = 20,
  stroke = 'var(--color-checkbox-primary-stroke, #3D405B)',
  ...props
}) => (
  <svg viewBox="0 0 24 24" width={size} height={size} fill="none" aria-hidden="true" {...props}>
    <circle cx="12" cy="12" r="9" stroke={stroke} strokeWidth="2" />
  </svg>
);

/** 5. Error Checked (Solid Red Fill Circle + Inner White Checkmark Tick) */
export const CheckboxErrorCheckedIconSvg = ({
  size = 24,
  fill = 'var(--color-checkbox-error-fill, #C00F48)',
  tickColor = 'var(--color-checkbox-error-tick, #FFFFFF)',
  ...props
}) => (
  <svg viewBox="0 0 24 24" width={size} height={size} fill="none" aria-hidden="true" {...props}>
    <circle cx="12" cy="12" r="10" fill={fill} />
    <polyline points="8 12 11 15 16 9" fill="none" stroke={tickColor} strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
  </svg>
);

/** 6. Error Checked Light (Red Outline Circle + Inner Red Checkmark Tick) */
export const CheckboxErrorCheckedLightIconSvg = ({
  size = 24,
  stroke = 'var(--color-checkbox-error-stroke, #C00F48)',
  ...props
}) => (
  <svg viewBox="0 0 24 24" width={size} height={size} fill="none" aria-hidden="true" {...props}>
    <circle cx="12" cy="12" r="9" stroke={stroke} strokeWidth="2" />
    <polyline points="8 12 11 15 16 9" fill="none" stroke={stroke} strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
  </svg>
);

/** 7. Error Indeterminate (Red Outline Circle + Inner Red Horizontal Dash) */
export const CheckboxErrorIndeterminateIconSvg = ({
  size = 20,
  stroke = 'var(--color-checkbox-error-stroke, #C00F48)',
  ...props
}) => (
  <svg viewBox="0 0 24 24" width={size} height={size} fill="none" aria-hidden="true" {...props}>
    <circle cx="12" cy="12" r="9" stroke={stroke} strokeWidth="2" />
    <line x1="7" y1="12" x2="17" y2="12" stroke={stroke} strokeWidth="2.5" strokeLinecap="round" />
  </svg>
);

/** 8. Error Unchecked (Red Empty Outline Circle) */
export const CheckboxErrorUncheckedIconSvg = ({
  size = 20,
  stroke = 'var(--color-checkbox-error-stroke, #C00F48)',
  ...props
}) => (
  <svg viewBox="0 0 24 24" width={size} height={size} fill="none" aria-hidden="true" {...props}>
    <circle cx="12" cy="12" r="9" stroke={stroke} strokeWidth="2" />
  </svg>
);


/* ==========================================================================
   MAIN CHECKBOX COMPONENT (64 VARIANTS MATRIX SUPPORT)
   ========================================================================== */

/**
 * Checkbox Component - KPMG WorkBench Design System
 * 64 Figma Variants (8 Types × 4 States × 2 Sizes).
 * Formatted directly to Figma specifications with token design system integration and custom SVG props support.
 */
export const Checkbox = forwardRef(({
  size = 'large', // 'large' (40px touch container) | 'small' (24px touch container)
  type, // 'checked' | 'unchecked-light' | 'indeterminate' | 'unchecked' | 'error-checked' | 'error-checked-light' | 'error-indeterminate' | 'error-unchecked'
  state = 'enabled', // 'enabled' | 'disabled' | 'hovered' | 'pressed'
  checked,
  indeterminate,
  error = false,
  disabled = false,
  label,
  subtext,
  icon: customIconProp,
  onChange,
  className = '',
  id,
  name,
  value,
  ...props
}, ref) => {
  // Normalize size parameter ('large' / 'Large', 'small' / 'Small')
  const normalizedSize = (size || 'large').toLowerCase();
  
  // Normalize disabled state
  const isComponentDisabled = disabled || state === 'disabled' || state === 'Disabled';
  const normalizedState = isComponentDisabled ? 'disabled' : (state || 'enabled').toLowerCase();

  // Resolve active type variant based on props (support both explicit `type` prop and boolean flags)
  let activeType = type;

  if (!activeType) {
    if (error) {
      if (indeterminate) activeType = 'error-indeterminate';
      else if (checked) activeType = 'error-checked';
      else activeType = 'error-unchecked';
    } else {
      if (indeterminate) activeType = 'indeterminate';
      else if (checked) activeType = 'checked';
      else activeType = 'unchecked';
    }
  }

  // Icon dimension per size scale
  const iconPixelSize = normalizedSize === 'small' ? 16 : 24;
  const smallSubIconPixelSize = normalizedSize === 'small' ? 14 : 20;

  // Render SVG Icon per active variant type
  const renderIcon = () => {
    if (customIconProp) return customIconProp;

    const isDisabled = isComponentDisabled;
    const primaryDisabledColor = 'var(--color-checkbox-disabled-stroke, #9090A2)';

    switch (activeType) {
      case 'checked':
      case 'Checked':
        return (
          <CheckboxCheckedIconSvg
            size={iconPixelSize}
            fill={isDisabled ? primaryDisabledColor : 'var(--color-checkbox-primary-fill, #3D405B)'}
          />
        );

      case 'unchecked-light':
      case 'Unchecked light':
      case 'unchecked_light':
        return (
          <CheckboxUncheckedLightIconSvg
            size={iconPixelSize}
            stroke={isDisabled ? primaryDisabledColor : 'var(--color-checkbox-primary-stroke, #3D405B)'}
          />
        );

      case 'indeterminate':
      case 'Indeterminate':
        return (
          <CheckboxIndeterminateIconSvg
            size={smallSubIconPixelSize}
            stroke={isDisabled ? primaryDisabledColor : 'var(--color-checkbox-primary-stroke, #3D405B)'}
          />
        );

      case 'unchecked':
      case 'Unchecked':
        return (
          <CheckboxUncheckedIconSvg
            size={smallSubIconPixelSize}
            stroke={isDisabled ? primaryDisabledColor : 'var(--color-checkbox-primary-stroke, #3D405B)'}
          />
        );

      case 'error-checked':
      case 'Error checked':
      case 'error_checked':
        return (
          <CheckboxErrorCheckedIconSvg
            size={iconPixelSize}
            fill={isDisabled ? primaryDisabledColor : 'var(--color-checkbox-error-fill, #C00F48)'}
          />
        );

      case 'error-checked-light':
      case 'Error checked light':
      case 'error_checked_light':
        return (
          <CheckboxErrorCheckedLightIconSvg
            size={iconPixelSize}
            stroke={isDisabled ? primaryDisabledColor : 'var(--color-checkbox-error-stroke, #C00F48)'}
          />
        );

      case 'error-indeterminate':
      case 'Error indeterminate':
      case 'error_indeterminate':
        return (
          <CheckboxErrorIndeterminateIconSvg
            size={smallSubIconPixelSize}
            stroke={isDisabled ? primaryDisabledColor : 'var(--color-checkbox-error-stroke, #C00F48)'}
          />
        );

      case 'error-unchecked':
      case 'Error unchecked':
      case 'error_unchecked':
      default:
        return (
          <CheckboxErrorUncheckedIconSvg
            size={smallSubIconPixelSize}
            stroke={isDisabled ? primaryDisabledColor : 'var(--color-checkbox-error-stroke, #C00F48)'}
          />
        );
    }
  };

  const isCheckedState =
    activeType === 'checked' ||
    activeType === 'Checked' ||
    activeType === 'unchecked-light' ||
    activeType === 'Unchecked light' ||
    activeType === 'error-checked' ||
    activeType === 'Error checked' ||
    activeType === 'error-checked-light' ||
    activeType === 'Error checked light';

  const containerClasses = [
    'kpmg-checkbox',
    `kpmg-checkbox--${normalizedSize}`,
    `kpmg-checkbox--state-${normalizedState}`,
    `kpmg-checkbox--type-${String(activeType).toLowerCase().replace(/\s+/g, '-')}`,
    isComponentDisabled ? 'kpmg-checkbox--disabled' : '',
    className,
  ].filter(Boolean).join(' ');

  return (
    <label className={containerClasses}>
      {/* Hidden native checkbox input for accessibility and form integration */}
      <input
        type="checkbox"
        ref={ref}
        id={id}
        name={name}
        value={value}
        checked={checked !== undefined ? checked : isCheckedState}
        disabled={isComponentDisabled}
        onChange={onChange}
        className="kpmg-checkbox__native-input"
        {...props}
      />

      {/* Visual Touch Target Box & State Layer Overlay */}
      <span className="kpmg-checkbox__box" aria-hidden="true">
        {renderIcon()}
      </span>

      {/* Optional Label & Subtext */}
      {(label || subtext) && (
        <span className="kpmg-checkbox__label-container">
          {label && <span className="kpmg-checkbox__label">{label}</span>}
          {subtext && <span className="kpmg-checkbox__subtext">{subtext}</span>}
        </span>
      )}
    </label>
  );
});

Checkbox.displayName = 'Checkbox';

Checkbox.propTypes = {
  /** Size variant scale ('large' = 40px outer container, 'small' = 24px outer container) */
  size: PropTypes.oneOf(['large', 'small', 'Large', 'Small']),
  /** Explicit Figma variant type (8 choices) */
  type: PropTypes.oneOf([
    'checked',
    'Checked',
    'unchecked-light',
    'Unchecked light',
    'indeterminate',
    'Indeterminate',
    'unchecked',
    'Unchecked',
    'error-checked',
    'Error checked',
    'error-checked-light',
    'Error checked light',
    'error-indeterminate',
    'Error indeterminate',
    'error-unchecked',
    'Error unchecked',
  ]),
  /** Explicit interactive state ('enabled', 'disabled', 'hovered', 'pressed') */
  state: PropTypes.oneOf(['enabled', 'disabled', 'hovered', 'pressed', 'Enabled', 'Disabled', 'Hovered', 'Pressed']),
  /** Controlled checked status */
  checked: PropTypes.bool,
  /** Controlled indeterminate status */
  indeterminate: PropTypes.bool,
  /** Error state flag */
  error: PropTypes.bool,
  /** Disabled state flag */
  disabled: PropTypes.bool,
  /** Label text or Node */
  label: PropTypes.node,
  /** Subtext description below label */
  subtext: PropTypes.node,
  /** Custom SVG Icon prop override */
  icon: PropTypes.node,
  /** Change event handler callback */
  onChange: PropTypes.func,
  /** Custom CSS class name */
  className: PropTypes.string,
  /** HTML input id attribute */
  id: PropTypes.string,
  /** HTML input name attribute */
  name: PropTypes.string,
  /** HTML input value attribute */
  value: PropTypes.string,
};

export default Checkbox;

// packages/angular/src/lib/checkbox/checkbox.component.ts
import { booleanAttribute, ChangeDetectionStrategy, Component, computed, input, model, output, TemplateRef } from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';

export type CheckboxSize = 'large' | 'small';
export type CheckboxState = 'enabled' | 'disabled' | 'hovered' | 'pressed';
export type CheckboxType =
  | 'checked'
  | 'unchecked-light'
  | 'indeterminate'
  | 'unchecked'
  | 'error-checked'
  | 'error-checked-light'
  | 'error-indeterminate'
  | 'error-unchecked';

const CHECKED_TYPES: readonly string[] = ['checked', 'unchecked-light', 'error-checked', 'error-checked-light'];
const DISABLED_COLOR = 'var(--color-checkbox-disabled-stroke, #9090A2)';

/**
 * WorkBench Checkbox — mirrors packages/ui/src/components/Checkbox/Checkbox.jsx
 * (8 types × 4 states × 2 sizes). `checked` is a model: bind `[(checked)]`
 * or listen to `(checkedChange)`.
 */
@Component({
  selector: 'kpmg-checkbox',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgTemplateOutlet],
  host: { style: 'display: contents' },
  template: `
    <label [class]="classes()">
      <input
        type="checkbox"
        class="kpmg-checkbox__native-input"
        [attr.id]="inputId()"
        [attr.name]="name()"
        [attr.value]="value()"
        [checked]="isChecked()"
        [disabled]="isDisabled()"
        (change)="onChange($event)"
      />
      <span class="kpmg-checkbox__box" aria-hidden="true">
        @if (icon(); as customIcon) {
          <ng-container [ngTemplateOutlet]="customIcon" />
        } @else {
        @switch (activeType()) {
          @case ('checked') {
            <svg [attr.width]="iconPx()" [attr.height]="iconPx()" viewBox="0 0 24 24" fill="none" aria-hidden="true">
              <circle cx="12" cy="12" r="10" [attr.fill]="isDisabled() ? disabledColor : 'var(--color-checkbox-primary-fill, #3D405B)'" />
              <polyline points="8 12 11 15 16 9" fill="none" stroke="var(--color-checkbox-primary-tick, #FFFFFF)" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
          }
          @case ('unchecked-light') {
            <svg [attr.width]="iconPx()" [attr.height]="iconPx()" viewBox="0 0 24 24" fill="none" aria-hidden="true">
              <circle cx="12" cy="12" r="9" [attr.stroke]="isDisabled() ? disabledColor : 'var(--color-checkbox-primary-stroke, #3D405B)'" stroke-width="2" />
              <polyline points="8 12 11 15 16 9" fill="none" [attr.stroke]="isDisabled() ? disabledColor : 'var(--color-checkbox-primary-stroke, #3D405B)'" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
          }
          @case ('indeterminate') {
            <svg [attr.width]="subIconPx()" [attr.height]="subIconPx()" viewBox="0 0 24 24" fill="none" aria-hidden="true">
              <circle cx="12" cy="12" r="9" [attr.stroke]="isDisabled() ? disabledColor : 'var(--color-checkbox-primary-stroke, #3D405B)'" stroke-width="2" />
              <line x1="7" y1="12" x2="17" y2="12" [attr.stroke]="isDisabled() ? disabledColor : 'var(--color-checkbox-primary-stroke, #3D405B)'" stroke-width="2.5" stroke-linecap="round" />
            </svg>
          }
          @case ('unchecked') {
            <svg [attr.width]="subIconPx()" [attr.height]="subIconPx()" viewBox="0 0 24 24" fill="none" aria-hidden="true">
              <circle cx="12" cy="12" r="9" [attr.stroke]="isDisabled() ? disabledColor : 'var(--color-checkbox-primary-stroke, #3D405B)'" stroke-width="2" />
            </svg>
          }
          @case ('error-checked') {
            <svg [attr.width]="iconPx()" [attr.height]="iconPx()" viewBox="0 0 24 24" fill="none" aria-hidden="true">
              <circle cx="12" cy="12" r="10" [attr.fill]="isDisabled() ? disabledColor : 'var(--color-checkbox-error-fill, #C00F48)'" />
              <polyline points="8 12 11 15 16 9" fill="none" stroke="var(--color-checkbox-primary-tick, #FFFFFF)" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
          }
          @case ('error-checked-light') {
            <svg [attr.width]="iconPx()" [attr.height]="iconPx()" viewBox="0 0 24 24" fill="none" aria-hidden="true">
              <circle cx="12" cy="12" r="9" [attr.stroke]="isDisabled() ? disabledColor : 'var(--color-checkbox-error-stroke, #C00F48)'" stroke-width="2" />
              <polyline points="8 12 11 15 16 9" fill="none" [attr.stroke]="isDisabled() ? disabledColor : 'var(--color-checkbox-error-stroke, #C00F48)'" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
          }
          @case ('error-indeterminate') {
            <svg [attr.width]="subIconPx()" [attr.height]="subIconPx()" viewBox="0 0 24 24" fill="none" aria-hidden="true">
              <circle cx="12" cy="12" r="9" [attr.stroke]="isDisabled() ? disabledColor : 'var(--color-checkbox-error-stroke, #C00F48)'" stroke-width="2" />
              <line x1="7" y1="12" x2="17" y2="12" [attr.stroke]="isDisabled() ? disabledColor : 'var(--color-checkbox-error-stroke, #C00F48)'" stroke-width="2.5" stroke-linecap="round" />
            </svg>
          }
          @default {
            <svg [attr.width]="subIconPx()" [attr.height]="subIconPx()" viewBox="0 0 24 24" fill="none" aria-hidden="true">
              <circle cx="12" cy="12" r="9" [attr.stroke]="isDisabled() ? disabledColor : 'var(--color-checkbox-error-stroke, #C00F48)'" stroke-width="2" />
            </svg>
          }
        }
        }
      </span>
      @if (label() || subtext()) {
        <span class="kpmg-checkbox__label-container">
          @if (label()) { <span class="kpmg-checkbox__label">{{ label() }}</span> }
          @if (subtext()) { <span class="kpmg-checkbox__subtext">{{ subtext() }}</span> }
        </span>
      }
    </label>
  `,
})
export class CheckboxComponent {
  /** large = 40px touch container, small = 24px. */
  readonly size = input<CheckboxSize>('large');
  /** Explicit Figma variant; overrides `checked`/`indeterminate`/`error`. */
  readonly type = input<CheckboxType | undefined>(undefined);
  readonly state = input<CheckboxState>('enabled');
  /** Checked status. Two-way bindable: `[(checked)]`. */
  readonly checked = model<boolean | undefined>(undefined);
  readonly indeterminate = input(false, { transform: booleanAttribute });
  readonly error = input(false, { transform: booleanAttribute });
  readonly disabled = input(false, { transform: booleanAttribute });
  readonly label = input<string | undefined>(undefined);
  readonly subtext = input<string | undefined>(undefined);
  /** Native input id (named `inputId` so it isn't duplicated on the host element). */
  readonly inputId = input<string | undefined>(undefined);
  readonly name = input<string | undefined>(undefined);
  readonly value = input<string | undefined>(undefined);
  /** Custom icon template that replaces the default SVG. */
  readonly icon = input<TemplateRef<unknown> | null>(null);
  readonly className = input('');

  /** Native change event. */
  readonly changed = output<Event>();

  protected readonly disabledColor = DISABLED_COLOR;

  private readonly normalizedSize = computed(() => (this.size() || 'large').toLowerCase());
  protected readonly isDisabled = computed(() => this.disabled() || this.state() === 'disabled');
  private readonly normalizedState = computed(() => (this.isDisabled() ? 'disabled' : (this.state() || 'enabled').toLowerCase()));

  protected readonly activeType = computed<string>(() => {
    const explicit = this.type();
    if (explicit) return explicit;
    const prefix = this.error() ? 'error-' : '';
    if (this.indeterminate()) return `${prefix}indeterminate`;
    return `${prefix}${this.checked() ? 'checked' : 'unchecked'}`;
  });

  protected readonly isChecked = computed(() => this.checked() ?? CHECKED_TYPES.includes(this.activeType()));

  protected readonly iconPx = computed(() => (this.normalizedSize() === 'small' ? 16 : 24));
  protected readonly subIconPx = computed(() => (this.normalizedSize() === 'small' ? 14 : 20));

  protected readonly classes = computed(() =>
    [
      'kpmg-checkbox',
      `kpmg-checkbox--${this.normalizedSize()}`,
      `kpmg-checkbox--state-${this.normalizedState()}`,
      `kpmg-checkbox--type-${this.activeType().toLowerCase().replace(/\s+/g, '-')}`,
      this.isDisabled() ? 'kpmg-checkbox--disabled' : '',
      this.className(),
    ]
      .filter(Boolean)
      .join(' '),
  );

  protected onChange(event: Event): void {
    this.checked.set((event.target as HTMLInputElement).checked);
    this.changed.emit(event);
  }
}
