// packages/angular/src/lib/badge/badge.component.ts
import { booleanAttribute, ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export type BadgeSize = 'small' | 'medium' | 'large';
export type BadgeStyleType = 'primary' | 'neutral';
export type BadgeState = 'loud' | 'quiet';
export type BadgePlacement = 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left';

/**
 * WorkBench Badge — mirrors packages/ui/src/components/Badge/Badge.jsx.
 *
 * Deviation: Angular can't detect projected content, so set `anchored` when
 * wrapping an element (React infers this from `children`).
 */
@Component({
  selector: 'kpmg-badge',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    @if (anchored()) {
      <span class="kpmg-badge-container">
        <ng-content />
        @if (visible()) {
          <span [class]="classes()" [attr.role]="accessibleLabel() ? 'status' : null" [attr.aria-label]="accessibleLabel()">{{ displayContent() }}</span>
        }
      </span>
    } @else if (visible()) {
      <span [class]="classes()" [attr.role]="accessibleLabel() ? 'status' : null" [attr.aria-label]="accessibleLabel()">{{ displayContent() }}</span>
    }
  `,
})
export class BadgeComponent {
  readonly size = input<BadgeSize>('medium');
  readonly styleType = input<BadgeStyleType>('primary');
  /** Alias for `styleType`. */
  readonly variant = input<BadgeStyleType | undefined>(undefined);
  readonly state = input<BadgeState>('loud');
  /** Alias for `state`. */
  readonly intensity = input<BadgeState | undefined>(undefined);
  readonly count = input<number | string | undefined>(undefined);
  readonly maxCount = input(99);
  readonly showZero = input(false, { transform: booleanAttribute });
  readonly dot = input(false, { transform: booleanAttribute });
  readonly label = input<string | undefined>(undefined);
  readonly placement = input<BadgePlacement>('top-right');
  /** Force overlapping mode (defaults to `anchored`). */
  readonly overlap = input<boolean | undefined>(undefined);
  /** Set when projecting an element for the badge to anchor onto. */
  readonly anchored = input(false, { transform: booleanAttribute });
  readonly className = input('');
  readonly ariaLabel = input<string | undefined>(undefined);

  private readonly normalizedSize = computed(() => (this.size() || 'medium').toLowerCase());
  private readonly normalizedStyle = computed(() => (this.variant() || this.styleType() || 'primary').toLowerCase());
  private readonly normalizedState = computed(() => (this.intensity() || this.state() || 'loud').toLowerCase());

  protected readonly isDot = computed(
    () =>
      this.dot() ||
      this.normalizedSize() === 'small' ||
      (this.count() === undefined && this.label() === undefined && !this.anchored()),
  );

  protected readonly displayContent = computed<string | number | null>(() => {
    if (this.isDot() || this.normalizedSize() === 'small') return null;
    const label = this.label();
    if (label !== undefined && label !== null) return label;
    const count = this.count();
    if (typeof count === 'number') {
      return count > this.maxCount() ? `${this.maxCount()}+` : count;
    }
    return count ?? null;
  });

  /** A numeric zero hides the badge unless `showZero` is set. */
  protected readonly visible = computed(() => {
    const count = this.count();
    return !(!this.isDot() && this.label() === undefined && typeof count === 'number' && count === 0 && !this.showZero());
  });

  private readonly isOverlapping = computed(() => this.overlap() ?? this.anchored());

  protected readonly classes = computed(() =>
    [
      'kpmg-badge',
      `kpmg-badge--${this.normalizedSize()}`,
      `kpmg-badge--${this.normalizedStyle()}-${this.normalizedState()}`,
      this.isOverlapping() ? 'kpmg-badge--overlap' : '',
      this.isOverlapping() ? `kpmg-badge--overlap-${this.placement()}` : '',
      this.className(),
    ]
      .filter(Boolean)
      .join(' '),
  );

  protected readonly accessibleLabel = computed(() => {
    if (this.ariaLabel()) return this.ariaLabel();
    const count = this.count();
    if (typeof count === 'number') return `${count} notifications`;
    if (typeof this.label() === 'string') return this.label();
    return this.isDot() ? 'New notification' : undefined;
  });
}

// packages/ui/src/components/Badge/Badge.jsx
import React, { forwardRef } from 'react';
import PropTypes from 'prop-types';
import './Badge.css';

/**
 * KPMG Design System - Badge Component
 * 
 * Scalable, accessible badge component supporting 12 variants:
 * - 3 Sizes: Small (6px dot), Medium (16px count/pill), Large (24px count/pill)
 * - 2 Styles: Primary, Neutral
 * - 2 States / Intensities: Quiet, Loud
 * 
 * Can be used standalone or wrapped around interactive elements (buttons, icons, avatars).
 */
export const Badge = forwardRef(({
  size = 'medium',
  styleType = 'primary',
  variant,
  state = 'loud',
  intensity,
  count,
  maxCount = 99,
  showZero = false,
  dot = false,
  label,
  children,
  placement = 'top-right',
  overlap,
  className = '',
  style = {},
  'aria-label': ariaLabel,
  ...restProps
}, ref) => {
  // Normalize size, style, and intensity props
  const normalizedSize = (size || 'medium').toLowerCase();
  const normalizedStyle = (variant || styleType || 'primary').toLowerCase();
  const normalizedState = (intensity || state || 'loud').toLowerCase();

  // Determine if badge should render as a dot
  const isDot = dot || normalizedSize === 'small' || (count === undefined && label === undefined && !children);

  // Calculate display content for count/label
  let displayContent = null;
  if (!isDot && normalizedSize !== 'small') {
    if (label !== undefined && label !== null) {
      displayContent = label;
    } else if (typeof count === 'number') {
      if (count === 0 && !showZero) {
        return children ? <div className="kpmg-badge-container">{children}</div> : null;
      }
      displayContent = count > maxCount ? `${maxCount}+` : count;
    } else if (count !== undefined && count !== null) {
      displayContent = count;
    }
  }

  // Determine if this badge is attached to a child element
  const isOverlapping = overlap !== undefined ? overlap : Boolean(children);

  // Construct modifier classes
  const badgeClasses = [
    'kpmg-badge',
    `kpmg-badge--${normalizedSize}`,
    `kpmg-badge--${normalizedStyle}-${normalizedState}`,
    isOverlapping ? 'kpmg-badge--overlap' : '',
    isOverlapping ? `kpmg-badge--overlap-${placement}` : '',
    className,
  ].filter(Boolean).join(' ');

  // Compute accessible label
  const accessibleLabel = ariaLabel || (
    typeof count === 'number'
      ? `${count} notifications`
      : typeof label === 'string'
        ? label
        : isDot
          ? 'New notification'
          : undefined
  );

  const badgeElement = (
    <span
      ref={ref}
      className={badgeClasses}
      style={style}
      role={accessibleLabel ? 'status' : undefined}
      aria-label={accessibleLabel}
      {...restProps}
    >
      {normalizedSize !== 'small' && !isDot ? displayContent : null}
    </span>
  );

  // If wrapping a child component, render in a relative container
  if (children) {
    return (
      <span className="kpmg-badge-container">
        {children}
        {badgeElement}
      </span>
    );
  }

  return badgeElement;
});

Badge.displayName = 'Badge';

Badge.propTypes = {
  /** Size of badge: 'small' (6px dot), 'medium' (16px compact), 'large' (24px prominent) */
  size: PropTypes.oneOf(['small', 'medium', 'large', 'Small', 'Medium', 'Large']),
  /** Color theme style: 'primary' (brand blue) or 'neutral' (grayscale) */
  styleType: PropTypes.oneOf(['primary', 'neutral', 'Primary', 'Neutral']),
  /** Alias for styleType */
  variant: PropTypes.oneOf(['primary', 'neutral', 'Primary', 'Neutral']),
  /** Visual intensity/state: 'loud' (high contrast fill) or 'quiet' (subtle tint) */
  state: PropTypes.oneOf(['loud', 'quiet', 'Loud', 'Quiet']),
  /** Alias for state */
  intensity: PropTypes.oneOf(['loud', 'quiet', 'Loud', 'Quiet']),
  /** Numeric count to display */
  count: PropTypes.node,
  /** Maximum number to show before displaying ${maxCount}+ */
  maxCount: PropTypes.number,
  /** Whether to show badge when count is zero */
  showZero: PropTypes.bool,
  /** Render as a compact dot without text */
  dot: PropTypes.bool,
  /** Custom label content */
  label: PropTypes.node,
  /** Child component to anchor the badge onto */
  children: PropTypes.node,
  /** Position of overlapping badge when wrapping children */
  placement: PropTypes.oneOf(['top-right', 'top-left', 'bottom-right', 'bottom-left']),
  /** Force overlapping mode */
  overlap: PropTypes.bool,
  /** Additional CSS class name */
  className: PropTypes.string,
  /** Inline style overrides */
  style: PropTypes.object,
  /** ARIA label for screen readers */
  'aria-label': PropTypes.string,
};

export default Badge;
