// packages/angular/src/lib/data-table/data-table.component.ts
import { booleanAttribute, ChangeDetectionStrategy, Component, computed, input, linkedSignal, output, TemplateRef } from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';
import { DataTableCellComponent, DataTableCellState, DataTableDensity } from './data-table-cell.component';
import { DataTableHeaderComponent, DataTableHeaderState, DataTableHeaderType } from './data-table-header.component';
import { DataTableCheckboxIconComponent, DataTableSortDirection } from './data-table-icons.component';
import { DataTableTooltipProps } from './data-table-tooltip.component';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type DataTableRow = Record<string, any>;
export type DataTableRowKey = string | number;

/** Context for `DataTableColumn.cellTemplate` (React: `renderCell(value, row, rowIndex, column)`). */
export interface DataTableCellContext {
  $implicit: unknown;
  row: DataTableRow;
  rowIndex: number;
  column: DataTableColumn;
}

/** Context for `DataTableColumn.headerTemplate` (React: `renderHeader(column)`). */
export interface DataTableHeaderContext {
  $implicit: DataTableColumn;
}

export interface DataTableColumn {
  id?: string;
  key: string;
  label?: string;
  type?: 'text' | 'chip' | 'Text' | 'Chip';
  headerType?: DataTableHeaderType;
  headerState?: DataTableHeaderState;
  sortable?: boolean;
  width?: string;
  minWidth?: string;
  flex?: string;
  style?: Record<string, string | number>;
  cellState?: DataTableCellState | ((row: DataTableRow, rowIndex: number) => DataTableCellState);
  chipLabel?: string;
  errorText?: string;
  missingText?: string;
  tooltipProps?: DataTableTooltipProps;
  onActionClick?: (event: MouseEvent) => void;
  /** Custom header (React: `renderHeader`). */
  headerTemplate?: TemplateRef<DataTableHeaderContext>;
  /** Custom cell content (React: `renderCell`). */
  cellTemplate?: TemplateRef<DataTableCellContext>;
}

export interface DataTablePagination {
  page: number;
  pageSize: number;
  total?: number;
  serverSide?: boolean;
  onPageChange?: (page: number) => void;
}

export interface DataTableSelectionChange {
  keys: DataTableRowKey[];
  rows: DataTableRow[];
}
export interface DataTableSortChange {
  column: string | null;
  direction: DataTableSortDirection;
}
export interface DataTableCellClickEvent {
  value: unknown;
  row: DataTableRow;
  column: DataTableColumn;
  rowIndex: number;
  event: MouseEvent;
}
export interface DataTableActiveCellChange {
  key: string | null;
  value: unknown;
  row: DataTableRow;
  column: DataTableColumn;
  rowIndex: number;
}

const PLACEHOLDER_COLUMNS: DataTableColumn[] = [1, 2, 3, 4, 5, 6, 7, 8].map((n) => ({
  id: `col${n}`,
  key: `col${n}`,
  label: `Header ${n}`,
  width: '168px',
}));

/**
 * WorkBench DataTable — mirrors packages/ui/src/components/DataTable/DataTable.jsx.
 *
 * Deviations:
 * - Controlled/uncontrolled state is preserved: bind `selectedRowKeys`, `sortColumn`/`sortDirection`
 *   or `activeCellKey` to control them (leave `undefined` for internal state).
 * - Callbacks become outputs: `selectionChange`, `sortChange`, `cellClick`, `activeCellChange`, `pageChange`
 *   (`pagination.onPageChange` is also still called). `onRowClick` is not ported (React never invokes it).
 * - `renderHeader`/`renderCell` become `headerTemplate`/`cellTemplate` TemplateRefs on the column.
 * - `style` is `customStyle`. `hoverable` is accepted but, as in React, has no visual effect.
 */
@Component({
  selector: 'kpmg-data-table',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgTemplateOutlet, DataTableHeaderComponent, DataTableCellComponent, DataTableCheckboxIconComponent],
  host: { style: 'display: contents' },
  template: `
    <div [class]="'dt-root-wrapper ' + className()" [style]="rootStyle()">
      <div [class]="'dt-scroll-container ' + (scrollable() ? 'dt-scroll-container--scrollable' : '')">
        <div class="dt-table" role="table">
          <div class="dt-columns-wrapper" role="rowgroup">
            @if (selectable()) {
              <div class="dt-column dt-column--selection" style="width: 48px; flex-shrink: 0">
                <div class="dt-header-cell dt-header-cell--selection" (click)="handleSelectAll()" role="columnheader" aria-label="Select all rows">
                  <kpmg-data-table-checkbox-icon [checked]="isAllSelected()" [size]="20" color="#454554" />
                </div>
                <div class="dt-column-items">
                  @if (loading()) {
                    @for (n of loadingRows(); track n) {
                      <div class="dt-cell dt-cell--selection">
                        <kpmg-data-table-checkbox-icon [checked]="false" [size]="20" color="#b8b8c4" />
                      </div>
                    }
                  } @else {
                    @for (row of processedData(); track rowKeyAt(row, $index)) {
                      @let rowId = rowKeyAt(row, $index);
                      @let isSelected = selectedKeys().includes(rowId);
                      <div [class]="'dt-cell dt-cell--selection ' + (isSelected ? 'dt-cell--selected' : '')" (click)="handleSelectRow(rowId, $event)">
                        <kpmg-data-table-checkbox-icon [checked]="isSelected" [size]="20" [color]="isSelected ? '#1e49e2' : '#454554'" />
                      </div>
                    }
                  }
                </div>
              </div>
            }

            @for (col of effectiveColumns(); track $index; let colIdx = $index) {
              @let id = colId(col, colIdx);
              @let isColSorted = sortColumnValue() === id;
              <div class="dt-column" [style]="columnStyle(col)">
                @if (col.headerTemplate; as tpl) {
                  <ng-container [ngTemplateOutlet]="tpl" [ngTemplateOutletContext]="{ $implicit: col }" />
                } @else {
                  <kpmg-data-table-header
                    [title]="col.label || 'Header ' + (colIdx + 1)"
                    [type]="col.headerType || (col.sortable ? 'sort' : 'checkmark')"
                    [state]="col.headerState || (isColSorted ? 'Pressed' : 'Enabled')"
                    [pressed]="col.headerState === 'Pressed' || isColSorted"
                    [sortDirection]="isColSorted ? sortDirectionValue() : null"
                    [hasSortHandler]="!!col.sortable"
                    (sort)="handleSort(col)"
                    (actionClick)="col.onActionClick?.($event)"
                  />
                }

                <div class="dt-column-items">
                  @if (loading()) {
                    @for (n of loadingRows(); track n) {
                      <kpmg-data-table-cell state="loading" [density]="density()" />
                    }
                  } @else if (processedData().length === 0) {
                    @if (colIdx === 0) {
                      <div class="dt-empty-placeholder">{{ emptyMessage() }}</div>
                    }
                  } @else {
                    @for (row of processedData(); track rowKeyAt(row, $index); let rIdx = $index) {
                      @let rowId = rowKeyAt(row, rIdx);
                      @let cellKey = rowId + '_' + id;
                      @let rawValue = row[col.key];
                      @let isCellActive = activeCellKeyValue() === cellKey;
                      @let dynamicTooltip = tooltipGetter()?.(row, col, rIdx);
                      @if (col.cellTemplate; as cellTpl) {
                        <kpmg-data-table-cell
                          [type]="col.type || 'text'"
                          [state]="isCellActive ? 'Pressed' : cellStateFor(row, col, rIdx)"
                          [cellText]="rawValue !== undefined && rawValue !== null ? '' + rawValue : ''"
                          [chipLabel]="rawValue !== undefined && rawValue !== null ? '' + rawValue : col.chipLabel || 'Label'"
                          [errorText]="col.errorText || 'Error!'"
                          [missingText]="col.missingText || 'Missing data!'"
                          [withTooltip]="isCellActive || !!dynamicTooltip"
                          [tooltipProps]="dynamicTooltip || col.tooltipProps || {}"
                          [density]="density()"
                          [clickable]="true"
                          (cellClick)="handleCellClick(rawValue, row, col, rIdx, colIdx, $event)"
                        >
                          <ng-container [ngTemplateOutlet]="cellTpl" [ngTemplateOutletContext]="{ $implicit: rawValue, row: row, rowIndex: rIdx, column: col }" />
                        </kpmg-data-table-cell>
                      } @else {
                        <kpmg-data-table-cell
                          [type]="col.type || 'text'"
                          [state]="isCellActive ? 'Pressed' : cellStateFor(row, col, rIdx)"
                          [cellText]="rawValue !== undefined && rawValue !== null ? '' + rawValue : ''"
                          [chipLabel]="rawValue !== undefined && rawValue !== null ? '' + rawValue : col.chipLabel || 'Label'"
                          [errorText]="col.errorText || 'Error!'"
                          [missingText]="col.missingText || 'Missing data!'"
                          [withTooltip]="isCellActive || !!dynamicTooltip"
                          [tooltipProps]="dynamicTooltip || col.tooltipProps || {}"
                          [density]="density()"
                          [clickable]="true"
                          (cellClick)="handleCellClick(rawValue, row, col, rIdx, colIdx, $event)"
                        />
                      }
                    }
                  }
                </div>
              </div>
            }
          </div>
        </div>
      </div>

      @if (pagination(); as pg) {
        <div class="dt-pagination-container">
          <div class="dt-pagination-info">
            Showing {{ paginationFrom() }} to {{ paginationTo() }} of {{ paginationTotal() }} entries
          </div>
          <div class="dt-pagination-controls">
            <button type="button" class="dt-pagination-btn" [disabled]="pg.page <= 1" (click)="goToPage(pg.page - 1)">Previous</button>
            <span class="dt-pagination-page-indicator">Page {{ pg.page }} of {{ pageCount() || 1 }}</span>
            <button type="button" class="dt-pagination-btn" [disabled]="pg.page >= pageCount()" (click)="goToPage(pg.page + 1)">Next</button>
          </div>
        </div>
      }
    </div>
  `,
})
export class DataTableComponent {
  readonly columns = input<DataTableColumn[]>([]);
  readonly data = input<DataTableRow[]>([]);
  readonly rowKey = input<string | ((row: DataTableRow, index: number) => DataTableRowKey)>('id');
  readonly selectable = input(false, { transform: booleanAttribute });
  /** Controlled selection; leave `undefined` for internal state. */
  readonly selectedRowKeys = input<DataTableRowKey[] | undefined>(undefined);
  /** Controlled sort column; leave `undefined` for internal (client-side) sort. */
  readonly sortColumn = input<string | null | undefined>(undefined);
  readonly sortDirection = input<DataTableSortDirection | undefined>(undefined);
  readonly loading = input(false, { transform: booleanAttribute });
  readonly loadingRowCount = input(6);
  readonly density = input<DataTableDensity>('default');
  readonly hoverable = input(true, { transform: booleanAttribute });
  readonly cellStateGetter = input<((row: DataTableRow, col: DataTableColumn, rowIndex: number) => DataTableCellState | null | undefined) | undefined>(undefined);
  readonly tooltipGetter = input<((row: DataTableRow, col: DataTableColumn, rowIndex: number) => DataTableTooltipProps | null | undefined) | undefined>(undefined);
  /** Controlled active cell key (`<rowKey>_<columnId>`); leave `undefined` for internal state. */
  readonly activeCellKey = input<string | null | undefined>(undefined);
  readonly pagination = input<DataTablePagination | undefined>(undefined);
  readonly emptyMessage = input('No records available.');
  readonly width = input('100%');
  readonly height = input('100%');
  readonly scrollable = input(false, { transform: booleanAttribute });
  readonly className = input('');
  /** Inline styles for the root (React: `style`). */
  readonly customStyle = input<Record<string, string | number>>({});
  readonly tableWidth = input<string | undefined>(undefined);

  readonly selectionChange = output<DataTableSelectionChange>();
  readonly sortChange = output<DataTableSortChange>();
  readonly cellClick = output<DataTableCellClickEvent>();
  readonly activeCellChange = output<DataTableActiveCellChange>();
  readonly pageChange = output<number>();

  private readonly internalSelectedKeys = linkedSignal<DataTableRowKey[] | undefined, DataTableRowKey[]>({
    source: this.selectedRowKeys,
    computation: (src, prev) => src ?? prev?.value ?? [],
  });
  private readonly internalSortColumn = linkedSignal<string | null | undefined, string | null>({
    source: this.sortColumn,
    computation: (src, prev) => src ?? prev?.value ?? null,
  });
  private readonly internalSortDirection = linkedSignal<DataTableSortDirection | undefined, DataTableSortDirection>({
    source: this.sortDirection,
    computation: (src, prev) => src ?? prev?.value ?? null,
  });
  private readonly internalActiveCellKey = linkedSignal<string | null | undefined, string | null>({
    source: this.activeCellKey,
    computation: (src, prev) => src ?? prev?.value ?? null,
  });

  private readonly isSelectionControlled = computed(() => this.selectedRowKeys() !== undefined);
  private readonly isSortControlled = computed(() => this.sortColumn() !== undefined);
  private readonly isActiveCellControlled = computed(() => this.activeCellKey() !== undefined);

  protected readonly selectedKeys = computed(() => (this.isSelectionControlled() ? this.selectedRowKeys()! : this.internalSelectedKeys()));
  protected readonly sortColumnValue = computed(() => (this.isSortControlled() ? (this.sortColumn() ?? null) : this.internalSortColumn()));
  protected readonly sortDirectionValue = computed(() => (this.isSortControlled() ? (this.sortDirection() ?? null) : this.internalSortDirection()));
  protected readonly activeCellKeyValue = computed(() => (this.isActiveCellControlled() ? (this.activeCellKey() ?? null) : this.internalActiveCellKey()));

  protected readonly loadingRows = computed(() => Array.from({ length: this.loadingRowCount() }, (_, i) => i));

  protected readonly effectiveColumns = computed(() => (this.columns().length > 0 ? this.columns() : PLACEHOLDER_COLUMNS));

  protected readonly allRowKeys = computed(() => this.data().map((row, idx) => this.rowKeyAt(row, idx)));
  protected readonly isAllSelected = computed(() => {
    const keys = this.allRowKeys();
    return keys.length > 0 && keys.every((k) => this.selectedKeys().includes(k));
  });

  protected readonly processedData = computed<DataTableRow[]>(() => {
    const data = this.data();
    if (!data || data.length === 0) return [];
    let items = [...data];
    const sortCol = this.sortColumnValue();
    const dir = this.sortDirectionValue();
    if (!this.isSortControlled() && sortCol && dir) {
      const currentCol = this.columns().find((c) => (c.id || c.key) === sortCol);
      if (currentCol) {
        items.sort((a, b) => {
          const valA = a[currentCol.key];
          const valB = b[currentCol.key];
          if (valA === valB) return 0;
          if (valA === undefined || valA === null) return 1;
          if (valB === undefined || valB === null) return -1;
          const result = valA > valB ? 1 : -1;
          return dir === 'asc' ? result : -result;
        });
      }
    }
    const pg = this.pagination();
    if (pg && pg.page && pg.pageSize && !pg.serverSide) {
      const start = (pg.page - 1) * pg.pageSize;
      items = items.slice(start, start + pg.pageSize);
    }
    return items;
  });

  protected readonly rootStyle = computed(() => {
    const width = this.width();
    const height = this.height();
    const tableWidth = this.tableWidth();
    return {
      width: width || '100%',
      height: height === '100%' ? 'auto' : height || 'auto',
      minHeight: 'fit-content',
      ...(tableWidth ? { maxWidth: tableWidth } : {}),
      ...this.customStyle(),
    };
  });

  protected readonly paginationTotal = computed(() => {
    const pg = this.pagination();
    return pg ? pg.total || this.data().length : 0;
  });
  protected readonly paginationFrom = computed(() => {
    const pg = this.pagination();
    return pg ? Math.min((pg.page - 1) * pg.pageSize + 1, this.paginationTotal()) : 0;
  });
  protected readonly paginationTo = computed(() => {
    const pg = this.pagination();
    return pg ? Math.min(pg.page * pg.pageSize, this.paginationTotal()) : 0;
  });
  protected readonly pageCount = computed(() => {
    const pg = this.pagination();
    return pg ? Math.ceil(this.paginationTotal() / pg.pageSize) : 0;
  });

  protected rowKeyAt(row: DataTableRow, index: number): DataTableRowKey {
    const rk = this.rowKey();
    if (typeof rk === 'function') return rk(row, index);
    if (typeof row === 'object' && row !== null && rk in row) return row[rk];
    return index;
  }

  protected colId(col: DataTableColumn, index: number): string {
    return col.id || col.key || `col-${index}`;
  }

  protected columnStyle(col: DataTableColumn): Record<string, string | number> {
    const flex = col.flex || (col.width ? `1 1 ${col.width}` : '1 1 0%');
    return { flex, minWidth: col.minWidth || '120px', ...col.style };
  }

  protected cellStateFor(row: DataTableRow, col: DataTableColumn, rowIndex: number): DataTableCellState {
    const getter = this.cellStateGetter();
    if (getter) return getter(row, col, rowIndex) || 'Enabled';
    if (col.cellState) return typeof col.cellState === 'function' ? col.cellState(row, rowIndex) : col.cellState;
    return 'Enabled';
  }

  private emitSelection(nextKeys: DataTableRowKey[]): void {
    if (!this.isSelectionControlled()) this.internalSelectedKeys.set(nextKeys);
    const rows = this.data().filter((r, idx) => nextKeys.includes(this.rowKeyAt(r, idx)));
    this.selectionChange.emit({ keys: nextKeys, rows });
  }

  protected handleSelectAll(): void {
    this.emitSelection(this.isAllSelected() ? [] : [...this.allRowKeys()]);
  }

  protected handleSelectRow(key: DataTableRowKey, event: Event): void {
    event.stopPropagation();
    const current = this.selectedKeys();
    this.emitSelection(current.includes(key) ? current.filter((k) => k !== key) : [...current, key]);
  }

  protected handleSort(column: DataTableColumn): void {
    const colId = column.id || column.key;
    let next: DataTableSortDirection = 'asc';
    if (this.sortColumnValue() === colId) {
      if (this.sortDirectionValue() === 'asc') next = 'desc';
      else if (this.sortDirectionValue() === 'desc') next = null;
    }
    if (!this.isSortControlled()) {
      this.internalSortColumn.set(next ? colId : null);
      this.internalSortDirection.set(next);
    }
    this.sortChange.emit({ column: colId, direction: next });
  }

  protected handleCellClick(value: unknown, row: DataTableRow, col: DataTableColumn, rowIdx: number, colIdx: number, event: MouseEvent): void {
    const cellKey = `${this.rowKeyAt(row, rowIdx)}_${col.id || col.key || colIdx}`;
    const nextActive = this.activeCellKeyValue() === cellKey ? null : cellKey;
    if (!this.isActiveCellControlled()) this.internalActiveCellKey.set(nextActive);
    this.activeCellChange.emit({ key: nextActive, value, row, column: col, rowIndex: rowIdx });
    this.cellClick.emit({ value, row, column: col, rowIndex: rowIdx, event });
  }

  protected goToPage(page: number): void {
    this.pagination()?.onPageChange?.(page);
    this.pageChange.emit(page);
  }
}

// packages/ui/src/components/DataTable/DataTable.jsx
import React, { useState, useMemo } from 'react';
import DataTableHeader from './DataTableHeader';
import DataTableCell from './DataTableCell';
import { DataTableCheckboxIcon } from './DataTableIcons';
import './DataTable.css';

/**
 * DataTable Component
 * Enterprise scalable data table component engineered to KPMG WorkBench specifications.
 * Highly configurable through props with complete support for all Figma headers, cells, shimmer loaders, and tooltips.
 */
export const DataTable = ({
  columns = [],
  data = [],
  rowKey = 'id',
  selectable = false,
  selectedRowKeys: controlledSelectedKeys,
  onSelectionChange,
  sortColumn: controlledSortColumn,
  sortDirection: controlledSortDirection,
  onSort,
  loading = false,
  loadingRowCount = 6,
  density = 'default', // 'default' | 'dense'
  hoverable = true,
  onRowClick,
  onCellClick,
  cellStateGetter,
  tooltipGetter,
  activeCellKey: controlledActiveCellKey,
  onActiveCellChange,
  pagination,
  emptyMessage = 'No records available.',
  width = '100%',
  height = '100%',
  scrollable = false,
  className = '',
  style = {},
  tableWidth,
}) => {
  // Internal state for uncontrolled usage
  const [internalSelectedKeys, setInternalSelectedKeys] = useState([]);
  const [internalSortColumn, setInternalSortColumn] = useState(null);
  const [internalSortDirection, setInternalSortDirection] = useState(null);
  const [internalActiveCellKey, setInternalActiveCellKey] = useState(null);
  const [hoveredRowKey, setHoveredRowKey] = useState(null);
  const [hoveredCellKey, setHoveredCellKey] = useState(null);

  const isSelectionControlled = controlledSelectedKeys !== undefined;
  const selectedRowKeys = isSelectionControlled ? controlledSelectedKeys : internalSelectedKeys;

  const isSortControlled = controlledSortColumn !== undefined;
  const sortColumn = isSortControlled ? controlledSortColumn : internalSortColumn;
  const sortDirection = isSortControlled ? controlledSortDirection : internalSortDirection;

  const isActiveCellControlled = controlledActiveCellKey !== undefined;
  const activeCellKey = isActiveCellControlled ? controlledActiveCellKey : internalActiveCellKey;

  // Row Key helper
  const getRowKey = (row, index) => {
    if (typeof rowKey === 'function') return rowKey(row, index);
    if (typeof row === 'object' && row !== null && rowKey in row) return row[rowKey];
    return index;
  };

  // Selection handlers
  const allRowKeys = useMemo(() => {
    return data.map((row, idx) => getRowKey(row, idx));
  }, [data, rowKey]);

  const isAllSelected = allRowKeys.length > 0 && allRowKeys.every((key) => selectedRowKeys.includes(key));
  const isPartiallySelected = !isAllSelected && allRowKeys.some((key) => selectedRowKeys.includes(key));

  const handleSelectAll = () => {
    const nextKeys = isAllSelected ? [] : [...allRowKeys];
    if (!isSelectionControlled) {
      setInternalSelectedKeys(nextKeys);
    }
    if (onSelectionChange) {
      const selectedRows = data.filter((row, idx) => nextKeys.includes(getRowKey(row, idx)));
      onSelectionChange(nextKeys, selectedRows);
    }
  };

  const handleSelectRow = (key, row, e) => {
    e.stopPropagation();
    let nextKeys;
    if (selectedRowKeys.includes(key)) {
      nextKeys = selectedRowKeys.filter((k) => k !== key);
    } else {
      nextKeys = [...selectedRowKeys, key];
    }

    if (!isSelectionControlled) {
      setInternalSelectedKeys(nextKeys);
    }
    if (onSelectionChange) {
      const selectedRows = data.filter((r, idx) => nextKeys.includes(getRowKey(r, idx)));
      onSelectionChange(nextKeys, selectedRows);
    }
  };

  // Sort handler
  const handleSort = (column) => {
    const colId = column.id || column.key;
    let nextDirection = 'asc';

    if (sortColumn === colId) {
      if (sortDirection === 'asc') nextDirection = 'desc';
      else if (sortDirection === 'desc') nextDirection = null;
    }

    if (!isSortControlled) {
      setInternalSortColumn(nextDirection ? colId : null);
      setInternalSortDirection(nextDirection);
    }
    if (onSort) {
      onSort(colId, nextDirection);
    }
  };

  // Cell click handler
  const handleCellClick = (val, row, col, rowIdx, colIdx, e) => {
    const cellKey = `${getRowKey(row, rowIdx)}_${col.id || col.key || colIdx}`;
    const nextActiveKey = activeCellKey === cellKey ? null : cellKey;

    if (!isActiveCellControlled) {
      setInternalActiveCellKey(nextActiveKey);
    }
    if (onActiveCellChange) {
      onActiveCellChange(nextActiveKey, { value: val, row, column: col, rowIndex: rowIdx });
    }
    if (onCellClick) {
      onCellClick(val, row, col, rowIdx, e);
    }
  };

  // Sorted and Paginated data
  const processedData = useMemo(() => {
    if (!data || data.length === 0) return [];
    let items = [...data];

    // Local client-side sort if not controlled and column marked sortable
    if (!isSortControlled && sortColumn && sortDirection) {
      const currentCol = columns.find((c) => (c.id || c.key) === sortColumn);
      if (currentCol) {
        items.sort((a, b) => {
          const valA = a[currentCol.key];
          const valB = b[currentCol.key];
          if (valA === valB) return 0;
          if (valA === undefined || valA === null) return 1;
          if (valB === undefined || valB === null) return -1;
          const result = valA > valB ? 1 : -1;
          return sortDirection === 'asc' ? result : -result;
        });
      }
    }

    // Local pagination if provided
    if (pagination && pagination.page && pagination.pageSize && !pagination.serverSide) {
      const start = (pagination.page - 1) * pagination.pageSize;
      items = items.slice(start, start + pagination.pageSize);
    }

    return items;
  }, [data, isSortControlled, sortColumn, sortDirection, columns, pagination]);

  // Loading skeleton placeholder columns
  const effectiveColumns = columns.length > 0 ? columns : [
    { id: 'col1', key: 'col1', label: 'Header 1', width: '168px' },
    { id: 'col2', key: 'col2', label: 'Header 2', width: '168px' },
    { id: 'col3', key: 'col3', label: 'Header 3', width: '168px' },
    { id: 'col4', key: 'col4', label: 'Header 4', width: '168px' },
    { id: 'col5', key: 'col5', label: 'Header 5', width: '168px' },
    { id: 'col6', key: 'col6', label: 'Header 6', width: '168px' },
    { id: 'col7', key: 'col7', label: 'Header 7', width: '168px' },
    { id: 'col8', key: 'col8', label: 'Header 8', width: '168px' },
  ];

  return (
    <div
      className={`dt-root-wrapper ${className}`}
      style={{
        width: width || '100%',
        height: height === '100%' ? 'auto' : (height || 'auto'),
        minHeight: 'fit-content',
        ...(tableWidth ? { maxWidth: tableWidth } : {}),
        ...style,
      }}
    >
      <div className={`dt-scroll-container ${scrollable ? 'dt-scroll-container--scrollable' : ''}`}>
        <div className="dt-table" role="table">
          {/* Column Layout Header Row */}
          <div className="dt-columns-wrapper" role="rowgroup">
            {selectable && (
              <div className="dt-column dt-column--selection" style={{ width: '48px', flexShrink: 0 }}>
                <div
                  className="dt-header-cell dt-header-cell--selection"
                  onClick={handleSelectAll}
                  role="columnheader"
                  aria-label="Select all rows"
                >
                  <DataTableCheckboxIcon
                    checked={isAllSelected}
                    size={20}
                    color="#454554"
                  />
                </div>
                <div className="dt-column-items">
                  {loading
                    ? Array.from({ length: loadingRowCount }).map((_, idx) => (
                        <div key={`skel-sel-${idx}`} className="dt-cell dt-cell--selection">
                          <DataTableCheckboxIcon checked={false} size={20} color="#b8b8c4" />
                        </div>
                      ))
                    : processedData.map((row, rIdx) => {
                        const rowId = getRowKey(row, rIdx);
                        const isSelected = selectedRowKeys.includes(rowId);
                        return (
                          <div
                            key={`sel-${rowId}`}
                            className={`dt-cell dt-cell--selection ${isSelected ? 'dt-cell--selected' : ''}`}
                            onClick={(e) => handleSelectRow(rowId, row, e)}
                          >
                            <DataTableCheckboxIcon
                              checked={isSelected}
                              size={20}
                              color={isSelected ? '#1e49e2' : '#454554'}
                            />
                          </div>
                        );
                      })}
                </div>
              </div>
            )}

            {/* Standard Columns */}
            {effectiveColumns.map((col, colIdx) => {
              const colId = col.id || col.key || `col-${colIdx}`;
              const colType = col.type || 'text';
              const isColSorted = sortColumn === colId;
              const colFlex = col.flex || (col.width ? `1 1 ${col.width}` : '1 1 0%');

              return (
                <div
                  key={colId}
                  className="dt-column"
                  style={{ flex: colFlex, minWidth: col.minWidth || '120px', ...col.style }}
                >
                  {/* Column Header */}
                  {col.renderHeader ? (
                    col.renderHeader(col)
                  ) : (
                    <DataTableHeader
                      title={col.label || `Header ${colIdx + 1}`}
                      type={col.headerType || (col.sortable ? 'sort' : 'checkmark')}
                      state={col.headerState || (isColSorted ? 'Pressed' : 'Enabled')}
                      pressed={col.headerState === 'Pressed' || isColSorted}
                      sortDirection={isColSorted ? sortDirection : null}
                      onSort={col.sortable ? () => handleSort(col) : undefined}
                      onActionClick={col.onActionClick}
                    />
                  )}

                  {/* Column Items */}
                  <div className="dt-column-items">
                    {loading ? (
                      Array.from({ length: loadingRowCount }).map((_, rIdx) => (
                        <DataTableCell
                          key={`loading-${colId}-${rIdx}`}
                          state="loading"
                          density={density}
                        />
                      ))
                    ) : processedData.length === 0 ? (
                      colIdx === 0 ? (
                        <div className="dt-empty-placeholder">{emptyMessage}</div>
                      ) : null
                    ) : (
                      processedData.map((row, rIdx) => {
                        const rowId = getRowKey(row, rIdx);
                        const cellKey = `${rowId}_${colId}`;
                        const rawValue = row[col.key];

                        // Determine dynamic cell state
                        let cellState = 'Enabled';
                        if (cellStateGetter) {
                          cellState = cellStateGetter(row, col, rIdx) || 'Enabled';
                        } else if (col.cellState) {
                          cellState = typeof col.cellState === 'function'
                            ? col.cellState(row, rIdx)
                            : col.cellState;
                        }

                        // Determine tooltip props if any
                        const isCellActive = activeCellKey === cellKey;
                        const dynamicTooltip = tooltipGetter ? tooltipGetter(row, col, rIdx) : null;
                        const hasTooltip = isCellActive || Boolean(dynamicTooltip);

                        // If active, force pressed state
                        const effectiveState = isCellActive ? 'Pressed' : cellState;

                        return (
                          <DataTableCell
                            key={cellKey}
                            type={colType}
                            state={effectiveState}
                            cellText={rawValue !== undefined && rawValue !== null ? String(rawValue) : ''}
                            chipLabel={rawValue !== undefined && rawValue !== null ? String(rawValue) : col.chipLabel || 'Label'}
                            errorText={col.errorText || 'Error!'}
                            missingText={col.missingText || 'Missing data!'}
                            withTooltip={hasTooltip}
                            tooltipProps={dynamicTooltip || col.tooltipProps || {}}
                            density={density}
                            onClick={(e) => handleCellClick(rawValue, row, col, rIdx, colIdx, e)}
                            onMouseEnter={() => {
                              if (hoverable) setHoveredCellKey(cellKey);
                            }}
                            onMouseLeave={() => {
                              if (hoverable && hoveredCellKey === cellKey) setHoveredCellKey(null);
                            }}
                          >
                            {col.renderCell ? col.renderCell(rawValue, row, rIdx, col) : undefined}
                          </DataTableCell>
                        );
                      })
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      {/* Pagination Controls */}
      {pagination && (
        <div className="dt-pagination-container">
          <div className="dt-pagination-info">
            Showing {Math.min((pagination.page - 1) * pagination.pageSize + 1, pagination.total || data.length)} to{' '}
            {Math.min(pagination.page * pagination.pageSize, pagination.total || data.length)} of{' '}
            {pagination.total || data.length} entries
          </div>
          <div className="dt-pagination-controls">
            <button
              type="button"
              className="dt-pagination-btn"
              disabled={pagination.page <= 1}
              onClick={() => pagination.onPageChange && pagination.onPageChange(pagination.page - 1)}
            >
              Previous
            </button>
            <span className="dt-pagination-page-indicator">
              Page {pagination.page} of {Math.ceil((pagination.total || data.length) / pagination.pageSize) || 1}
            </span>
            <button
              type="button"
              className="dt-pagination-btn"
              disabled={
                pagination.page >= Math.ceil((pagination.total || data.length) / pagination.pageSize)
              }
              onClick={() => pagination.onPageChange && pagination.onPageChange(pagination.page + 1)}
            >
              Next
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default DataTable;
