// packages/ui/src/components/Snackbar/Snackbar.jsx
import React, { useState, useEffect, useRef, forwardRef, createContext, useContext } from 'react';
import PropTypes from 'prop-types';
import './Snackbar.css';

/**
 * Close / Dismiss Icon (X)
 */
export const SnackbarCloseIcon = ({ size = 16, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    aria-hidden="true"
    className={className}
    {...props}
  >
    <line x1="18" y1="6" x2="6" y2="18" />
    <line x1="6" y1="6" x2="18" y2="18" />
  </svg>
);

SnackbarCloseIcon.propTypes = {
  size: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
  className: PropTypes.string,
};

/**
 * More Actions (Vertical Ellipsis) Icon
 */
export const SnackbarMoreIcon = ({ size = 16, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    aria-hidden="true"
    className={className}
    {...props}
  >
    <circle cx="12" cy="12" r="1" />
    <circle cx="12" cy="5" r="1" />
    <circle cx="12" cy="19" r="1" />
  </svg>
);

SnackbarMoreIcon.propTypes = {
  size: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
  className: PropTypes.string,
};

/**
 * KPMG WorkBench Snackbar Component
 *
 * Highly scalable, token-driven notification snackbar supporting:
 * - 10 Canonical Variants (5 Layout Sizes x 2 Outlines)
 * - Sizes: Single-line (64px), Two-line (76px), Extended (154px), Extended with header (194px), Extended with media (464px)
 * - Outline Treatments: Elevated (outline=false, resting shadow) & Outlined (outline=true, border stroke)
 * - Action buttons ("Action", "Longer action", or custom label) & dismiss close icon
 * - Up to 3 interactive media cards for rich content previews
 * - Timer auto-hide duration with pause on hover
 * - Full WAI-ARIA accessibility compliance (role="status" / role="alert")
 */
export const Snackbar = forwardRef(({
  open = true,
  message,
  header,
  description,
  size = 'single-line',
  outlined = false,
  action,
  actionLabel,
  onAction,
  closeable = true,
  onClose,
  autoHideDuration = null,
  items,
  role = 'status',
  className = '',
  style = {},
  ...restProps
}, ref) => {
  const [isVisible, setIsVisible] = useState(open);
  const timerRef = useRef(null);

  useEffect(() => {
    setIsVisible(open);
  }, [open]);

  // Auto-hide timer
  useEffect(() => {
    if (!isVisible || !autoHideDuration) return;

    timerRef.current = setTimeout(() => {
      handleClose();
    }, autoHideDuration);

    return () => {
      clearTimeout(timerRef.current);
    };
  }, [isVisible, autoHideDuration]);

  const handleMouseEnter = () => {
    if (timerRef.current) {
      clearTimeout(timerRef.current);
    }
  };

  const handleMouseLeave = () => {
    if (isVisible && autoHideDuration) {
      timerRef.current = setTimeout(() => {
        handleClose();
      }, autoHideDuration);
    }
  };

  const handleClose = () => {
    setIsVisible(false);
    if (onClose) {
      onClose();
    }
  };

  if (!isVisible) {
    return null;
  }

  // Derive effective action label & handler
  const resolvedActionLabel = actionLabel || (typeof action === 'string' ? action : (action?.label || null));
  const resolvedActionHandler = onAction || (action?.onClick || (() => {}));

  // Resolve size modifier
  const resolvedSizeClass = `kpmg-snackbar--${size}`;
  const resolvedOutlineClass = outlined ? 'kpmg-snackbar--outlined' : 'kpmg-snackbar--elevated';

  const snackbarClasses = [
    'kpmg-snackbar',
    resolvedSizeClass,
    resolvedOutlineClass,
    className,
  ].filter(Boolean).join(' ');

  // Default items for extended-media if none passed
  const mediaItems = items || (size === 'extended-media' ? [
    { id: '1', title: 'Header' },
    { id: '2', title: 'Header' },
    { id: '3', title: 'Header' },
  ] : []);

  // Action elements node
  const renderActions = () => {
    if (!resolvedActionLabel && !closeable && !React.isValidElement(action)) {
      return null;
    }

    return (
      <div className="kpmg-snackbar__actions">
        {React.isValidElement(action) ? (
          action
        ) : resolvedActionLabel ? (
          <button
            type="button"
            className="kpmg-snackbar__action-btn"
            onClick={resolvedActionHandler}
          >
            {resolvedActionLabel}
          </button>
        ) : null}

        {closeable && (
          <button
            type="button"
            className="kpmg-snackbar__close-btn"
            onClick={handleClose}
            aria-label="Dismiss notification"
          >
            <SnackbarCloseIcon size={16} />
          </button>
        )}
      </div>
    );
  };

  // Render layouts
  switch (size) {
    case 'single-line':
    case 'two-line':
      return (
        <div
          ref={ref}
          role={role}
          aria-live="polite"
          className={snackbarClasses}
          style={style}
          onMouseEnter={handleMouseEnter}
          onMouseLeave={handleMouseLeave}
          {...restProps}
        >
          <p className="kpmg-snackbar__message">
            {message || 'Snackbar text goes here'}
          </p>
          {renderActions()}
        </div>
      );

    case 'extended':
      return (
        <div
          ref={ref}
          role={role}
          aria-live="polite"
          className={snackbarClasses}
          style={style}
          onMouseEnter={handleMouseEnter}
          onMouseLeave={handleMouseLeave}
          {...restProps}
        >
          <div className="kpmg-snackbar__content">
            <p className="kpmg-snackbar__description">
              {description || message || 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'}
            </p>
          </div>
          {renderActions()}
        </div>
      );

    case 'extended-header':
      return (
        <div
          ref={ref}
          role={role}
          aria-live="polite"
          className={snackbarClasses}
          style={style}
          onMouseEnter={handleMouseEnter}
          onMouseLeave={handleMouseLeave}
          {...restProps}
        >
          <div className="kpmg-snackbar__content">
            <h4 className="kpmg-snackbar__header">
              {header || 'Header'}
            </h4>
            <p className="kpmg-snackbar__description">
              {description || message || 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'}
            </p>
          </div>
          {renderActions()}
        </div>
      );

    case 'extended-media':
      return (
        <div
          ref={ref}
          role={role}
          aria-live="polite"
          className={snackbarClasses}
          style={style}
          onMouseEnter={handleMouseEnter}
          onMouseLeave={handleMouseLeave}
          {...restProps}
        >
          <div className="kpmg-snackbar__content">
            <h4 className="kpmg-snackbar__header">
              {header || 'Header'}
            </h4>
            {(description || message) && (
              <p className="kpmg-snackbar__description">
                {description || message || 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'}
              </p>
            )}
            <div className="kpmg-snackbar__media-list">
              {mediaItems.map((item, idx) => (
                <div key={item.id || idx} className="kpmg-snackbar__media-item">
                  <div className="kpmg-snackbar__media-thumb" />
                  <div className="kpmg-snackbar__media-info">
                    <span className="kpmg-snackbar__media-title">{item.title}</span>
                    {item.subtitle && <span className="kpmg-snackbar__media-subtitle">{item.subtitle}</span>}
                  </div>
                  <button
                    type="button"
                    className="kpmg-snackbar__media-action"
                    onClick={item.onAction}
                    aria-label="More media options"
                  >
                    <SnackbarMoreIcon size={16} />
                  </button>
                </div>
              ))}
            </div>
          </div>
          {renderActions()}
        </div>
      );

    default:
      return (
        <div
          ref={ref}
          role={role}
          className={snackbarClasses}
          style={style}
          {...restProps}
        >
          <p className="kpmg-snackbar__message">{message}</p>
          {renderActions()}
        </div>
      );
  }
});

Snackbar.displayName = 'Snackbar';

Snackbar.propTypes = {
  /** Controls visibility of the snackbar */
  open: PropTypes.bool,
  /** Primary message text */
  message: PropTypes.node,
  /** Header title for extended variants */
  header: PropTypes.node,
  /** Detailed description text for extended variants */
  description: PropTypes.node,
  /** Size / layout form factor */
  size: PropTypes.oneOf([
    'single-line',
    'two-line',
    'extended',
    'extended-header',
    'extended-media',
  ]),
  /** Whether the snackbar has a border stroke (outline=true) or resting elevation shadow (outline=false) */
  outlined: PropTypes.bool,
  /** Action button configuration or custom React node */
  action: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.node,
    PropTypes.shape({
      label: PropTypes.string,
      onClick: PropTypes.func,
    }),
  ]),
  /** Action button text label (e.g. "Action", "Longer action") */
  actionLabel: PropTypes.string,
  /** Callback fired when action button is clicked */
  onAction: PropTypes.func,
  /** Whether the dismiss close (X) icon button is shown */
  closeable: PropTypes.bool,
  /** Callback fired when snackbar is closed or autoHide expires */
  onClose: PropTypes.func,
  /** Duration in milliseconds after which snackbar automatically closes (null to disable) */
  autoHideDuration: PropTypes.number,
  /** Media cards list for extended-media variant */
  items: PropTypes.arrayOf(
    PropTypes.shape({
      id: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
      title: PropTypes.string,
      subtitle: PropTypes.string,
      onAction: PropTypes.func,
    })
  ),
  /** ARIA accessibility role */
  role: PropTypes.string,
  /** Additional CSS class */
  className: PropTypes.string,
  /** Inline style overrides */
  style: PropTypes.object,
};

/* ==========================================================================
   Snackbar Viewport Container & Provider for Imperative Usage
   ========================================================================== */
export const SnackbarContext = createContext({
  showSnackbar: () => {},
  hideSnackbar: () => {},
});

export const useSnackbar = () => useContext(SnackbarContext);

export const SnackbarContainer = ({
  position = 'bottom-left',
  children,
  className = '',
}) => {
  return (
    <div className={`kpmg-snackbar-container kpmg-snackbar-container--${position} ${className}`}>
      {children}
    </div>
  );
};

SnackbarContainer.propTypes = {
  position: PropTypes.oneOf([
    'bottom-left',
    'bottom-center',
    'bottom-right',
    'top-left',
    'top-center',
    'top-right',
  ]),
  children: PropTypes.node,
  className: PropTypes.string,
};

export const SnackbarProvider = ({ children, defaultPosition = 'bottom-left' }) => {
  const [snackbars, setSnackbars] = useState([]);

  const showSnackbar = (options) => {
    const id = options.id || Date.now().toString();
    setSnackbars((prev) => [...prev, { ...options, id, open: true }]);
    return id;
  };

  const hideSnackbar = (id) => {
    setSnackbars((prev) => prev.filter((item) => item.id !== id));
  };

  return (
    <SnackbarContext.Provider value={{ showSnackbar, hideSnackbar }}>
      {children}
      <SnackbarContainer position={defaultPosition}>
        {snackbars.map((s) => (
          <Snackbar
            key={s.id}
            {...s}
            onClose={() => {
              hideSnackbar(s.id);
              if (s.onClose) s.onClose();
            }}
          />
        ))}
      </SnackbarContainer>
    </SnackbarContext.Provider>
  );
};

SnackbarProvider.propTypes = {
  children: PropTypes.node,
  defaultPosition: PropTypes.string,
};

export default Snackbar;

// packages/angular/src/lib/snackbar/snackbar.component.ts
import {
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  Injectable,
  inject,
  input,
  linkedSignal,
  output,
  signal,
  TemplateRef,
} from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';

export type SnackbarSize = 'single-line' | 'two-line' | 'extended' | 'extended-header' | 'extended-media';
export type SnackbarPosition = 'bottom-left' | 'bottom-center' | 'bottom-right' | 'top-left' | 'top-center' | 'top-right';

export interface SnackbarMediaItem {
  id?: string | number;
  title?: string;
  subtitle?: string;
  onAction?: (event: Event) => void;
}

export interface SnackbarActionConfig {
  label?: string;
  onClick?: (event: Event) => void;
}

const DEFAULT_DESCRIPTION =
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.';

/**
 * WorkBench Snackbar — mirrors packages/ui/src/components/Snackbar/Snackbar.jsx.
 *
 * Deviations: `onAction`/`onClose` are outputs `actionClick`/`closed`. `action`
 * accepts a string, `{ label, onClick }` or a `TemplateRef` (React: a node).
 * `message`/`header`/`description` are strings (React: ReactNode). `style` is
 * not ported (use host styling). Unknown sizes fall back to the message layout.
 */
@Component({
  selector: 'kpmg-snackbar',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgTemplateOutlet],
  host: { style: 'display: contents' },
  template: `
    @if (visible()) {
      <div
        [class]="classes()"
        [attr.role]="role()"
        [attr.aria-live]="isKnownSize() ? 'polite' : null"
        (mouseenter)="onMouseEnter()"
        (mouseleave)="onMouseLeave()"
      >
        @switch (size()) {
          @case ('single-line') {
            <p class="kpmg-snackbar__message">{{ message() || 'Snackbar text goes here' }}</p>
          }
          @case ('two-line') {
            <p class="kpmg-snackbar__message">{{ message() || 'Snackbar text goes here' }}</p>
          }
          @case ('extended') {
            <div class="kpmg-snackbar__content">
              <p class="kpmg-snackbar__description">{{ description() || message() || defaultDescription }}</p>
            </div>
          }
          @case ('extended-header') {
            <div class="kpmg-snackbar__content">
              <h4 class="kpmg-snackbar__header">{{ header() || 'Header' }}</h4>
              <p class="kpmg-snackbar__description">{{ description() || message() || defaultDescription }}</p>
            </div>
          }
          @case ('extended-media') {
            <div class="kpmg-snackbar__content">
              <h4 class="kpmg-snackbar__header">{{ header() || 'Header' }}</h4>
              @if (description() || message()) {
                <p class="kpmg-snackbar__description">{{ description() || message() || defaultDescription }}</p>
              }
              <div class="kpmg-snackbar__media-list">
                @for (item of mediaItems(); track item.id ?? $index) {
                  <div class="kpmg-snackbar__media-item">
                    <div class="kpmg-snackbar__media-thumb"></div>
                    <div class="kpmg-snackbar__media-info">
                      <span class="kpmg-snackbar__media-title">{{ item.title }}</span>
                      @if (item.subtitle) {
                        <span class="kpmg-snackbar__media-subtitle">{{ item.subtitle }}</span>
                      }
                    </div>
                    <button
                      type="button"
                      class="kpmg-snackbar__media-action"
                      (click)="item.onAction?.($event)"
                      aria-label="More media options"
                    >
                      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
                        <circle cx="12" cy="12" r="1" />
                        <circle cx="12" cy="5" r="1" />
                        <circle cx="12" cy="19" r="1" />
                      </svg>
                    </button>
                  </div>
                }
              </div>
            </div>
          }
          @default {
            <p class="kpmg-snackbar__message">{{ message() }}</p>
          }
        }
        @if (hasActions()) {
          <div class="kpmg-snackbar__actions">
            @if (actionTemplate(); as tpl) {
              <ng-container [ngTemplateOutlet]="tpl" />
            } @else if (resolvedActionLabel()) {
              <button type="button" class="kpmg-snackbar__action-btn" (click)="onActionClick($event)">
                {{ resolvedActionLabel() }}
              </button>
            }
            @if (closeable()) {
              <button type="button" class="kpmg-snackbar__close-btn" (click)="close()" aria-label="Dismiss notification">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
                  <line x1="18" y1="6" x2="6" y2="18" />
                  <line x1="6" y1="6" x2="18" y2="18" />
                </svg>
              </button>
            }
          </div>
        }
      </div>
    }
  `,
})
export class SnackbarComponent {
  protected readonly defaultDescription = DEFAULT_DESCRIPTION;

  readonly open = input(true, { transform: booleanAttribute });
  readonly message = input<string | undefined>(undefined);
  readonly header = input<string | undefined>(undefined);
  readonly description = input<string | undefined>(undefined);
  readonly size = input<SnackbarSize>('single-line');
  /** Border stroke (true) vs. resting elevation shadow (false). */
  readonly outlined = input(false, { transform: booleanAttribute });
  /** Label string, `{ label, onClick }`, or a template that replaces the action button. */
  readonly action = input<string | SnackbarActionConfig | TemplateRef<unknown> | undefined>(undefined);
  readonly actionLabel = input<string | undefined>(undefined);
  readonly closeable = input(true, { transform: booleanAttribute });
  /** Milliseconds before auto-close; `null` disables. Pauses while hovered. */
  readonly autoHideDuration = input<number | null>(null);
  /** Media cards for the `extended-media` size. */
  readonly items = input<SnackbarMediaItem[] | undefined>(undefined);
  readonly role = input('status');
  readonly className = input('');

  /** Action button click (React: `onAction`). */
  readonly actionClick = output<Event>();
  /** Dismissed or auto-hide expired (React: `onClose`). */
  readonly closed = output<void>();

  protected readonly visible = linkedSignal(() => this.open());
  private readonly hovered = signal(false);

  constructor() {
    effect((onCleanup) => {
      const duration = this.autoHideDuration();
      if (!this.visible() || !duration || this.hovered()) return;
      const timer = setTimeout(() => this.close(), duration);
      onCleanup(() => clearTimeout(timer));
    });
  }

  protected readonly isKnownSize = computed(() =>
    ['single-line', 'two-line', 'extended', 'extended-header', 'extended-media'].includes(this.size()),
  );

  protected readonly actionTemplate = computed(() => {
    const a = this.action();
    return a instanceof TemplateRef ? a : null;
  });

  protected readonly resolvedActionLabel = computed(() => {
    const a = this.action();
    if (this.actionLabel()) return this.actionLabel()!;
    if (typeof a === 'string') return a;
    if (a && !(a instanceof TemplateRef)) return a.label ?? null;
    return null;
  });

  protected readonly hasActions = computed(
    () => !!this.resolvedActionLabel() || this.closeable() || !!this.actionTemplate(),
  );

  protected readonly mediaItems = computed<SnackbarMediaItem[]>(
    () =>
      this.items() ??
      (this.size() === 'extended-media'
        ? [
            { id: '1', title: 'Header' },
            { id: '2', title: 'Header' },
            { id: '3', title: 'Header' },
          ]
        : []),
  );

  protected readonly classes = computed(() =>
    [
      'kpmg-snackbar',
      `kpmg-snackbar--${this.size()}`,
      this.outlined() ? 'kpmg-snackbar--outlined' : 'kpmg-snackbar--elevated',
      this.className(),
    ]
      .filter(Boolean)
      .join(' '),
  );

  protected onMouseEnter(): void {
    this.hovered.set(true);
  }

  protected onMouseLeave(): void {
    this.hovered.set(false);
  }

  protected onActionClick(event: Event): void {
    const a = this.action();
    if (a && typeof a === 'object' && !(a instanceof TemplateRef)) a.onClick?.(event);
    this.actionClick.emit(event);
  }

  protected close(): void {
    this.visible.set(false);
    this.closed.emit();
  }
}

/** Fixed viewport container for stacked snackbars — mirrors `SnackbarContainer`. */
@Component({
  selector: 'kpmg-snackbar-container',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `<div [class]="classes()"><ng-content /></div>`,
})
export class SnackbarContainerComponent {
  readonly position = input<SnackbarPosition>('bottom-left');
  readonly className = input('');

  protected readonly classes = computed(
    () => `kpmg-snackbar-container kpmg-snackbar-container--${this.position()} ${this.className()}`,
  );
}

export interface SnackbarOptions {
  id?: string;
  message?: string;
  header?: string;
  description?: string;
  size?: SnackbarSize;
  outlined?: boolean;
  action?: string | SnackbarActionConfig;
  actionLabel?: string;
  onAction?: (event: Event) => void;
  closeable?: boolean;
  autoHideDuration?: number | null;
  items?: SnackbarMediaItem[];
  role?: string;
  className?: string;
  onClose?: () => void;
}

/** Imperative API — replaces React's `SnackbarProvider` / `useSnackbar`. Render `<kpmg-snackbar-outlet>` once. */
@Injectable({ providedIn: 'root' })
export class SnackbarService {
  readonly snackbars = signal<(SnackbarOptions & { id: string })[]>([]);

  showSnackbar(options: SnackbarOptions): string {
    const id = options.id || Date.now().toString();
    this.snackbars.update((prev) => [...prev, { ...options, id }]);
    return id;
  }

  hideSnackbar(id: string): void {
    this.snackbars.update((prev) => prev.filter((s) => s.id !== id));
  }
}

/** Renders the snackbars queued through `SnackbarService` (React: the container inside `SnackbarProvider`). */
@Component({
  selector: 'kpmg-snackbar-outlet',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [SnackbarComponent, SnackbarContainerComponent],
  host: { style: 'display: contents' },
  template: `
    <kpmg-snackbar-container [position]="position()">
      @for (s of service.snackbars(); track s.id) {
        <kpmg-snackbar
          [message]="s.message"
          [header]="s.header"
          [description]="s.description"
          [size]="s.size ?? 'single-line'"
          [outlined]="s.outlined ?? false"
          [action]="s.action"
          [actionLabel]="s.actionLabel"
          [closeable]="s.closeable ?? true"
          [autoHideDuration]="s.autoHideDuration ?? null"
          [items]="s.items"
          [role]="s.role ?? 'status'"
          [className]="s.className ?? ''"
          (actionClick)="s.onAction?.($event)"
          (closed)="service.hideSnackbar(s.id); s.onClose?.()"
        />
      }
    </kpmg-snackbar-container>
  `,
})
export class SnackbarOutletComponent {
  protected readonly service = inject(SnackbarService);
  readonly position = input<SnackbarPosition>('bottom-left');
}
