// packages/angular/src/lib/dividers/dividers.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export type DividerOrientation = 'Horizontal' | 'Vertical' | 'horizontal' | 'vertical';
export type DividerTheme = 'Light' | 'Dark' | 'light' | 'dark';
export type DividerWidth =
  | 'Full'
  | 'Inset'
  | 'Inset middle small'
  | 'Inset middle medium'
  | 'Inset middle large'
  | 'Inset middle with text'
  | 'Inset middle'
  | 'full'
  | 'inset'
  | 'inset-middle-small'
  | 'inset-middle-medium'
  | 'inset-middle-large'
  | 'inset-middle-with-text'
  | 'inset-middle';

/**
 * WorkBench Dividers — mirrors packages/ui/src/components/Dividers/Dividers.jsx.
 *
 * Deviations: the React `style`/`...restProps` passthrough is omitted (style the
 * host element instead); `text` is a plain string rather than a ReactNode.
 */
@Component({
  selector: 'kpmg-dividers',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    @if (hasText()) {
      <div [attr.role]="role()" [attr.aria-orientation]="ariaOrientation()" [class]="classes()">
        <div class="kpmg-divider-line-wrapper"><div class="kpmg-divider-line"></div></div>
        @if (text()) {
          <div class="kpmg-divider-text-container"><p class="kpmg-divider-text">{{ text() }}</p></div>
        }
      </div>
    } @else {
      <div [attr.role]="role()" [attr.aria-orientation]="ariaOrientation()" [class]="classes()">
        <div class="kpmg-divider-line"></div>
      </div>
    }
  `,
})
export class DividersComponent {
  /** Orientation (alias: `orientation`). */
  readonly state = input<DividerOrientation>('Horizontal');
  /** Alias for `state`; takes precedence when set. */
  readonly orientation = input<DividerOrientation | undefined>(undefined);
  readonly theme = input<DividerTheme>('Light');
  readonly width = input<DividerWidth>('Full');
  /** Alias for `width`; takes precedence when set. */
  readonly variant = input<string | undefined>(undefined);
  /** Subheader text for the 'Inset middle with text' variant. */
  readonly text = input<string | undefined>('Subheader');
  readonly className = input('');
  readonly role = input('separator');
  readonly ariaOrientationOverride = input<'horizontal' | 'vertical' | undefined>(undefined, { alias: 'aria-orientation' });

  private readonly isVertical = computed(() => (this.orientation() || this.state() || 'Horizontal').toLowerCase() === 'vertical');
  private readonly effectiveOrientation = computed(() => (this.isVertical() ? 'vertical' : 'horizontal'));
  private readonly effectiveTheme = computed(() => ((this.theme() || 'Light').toLowerCase() === 'dark' ? 'dark' : 'light'));

  private readonly resolved = computed(() => {
    const rawWidth = this.variant() || this.width() || 'Full';
    const normalized = rawWidth.toLowerCase().replace(/\s+/g, '-');
    let modifier = 'kpmg-divider--full';
    let hasText = false;
    if (this.isVertical()) {
      if (normalized.includes('inset-middle')) modifier = 'kpmg-divider--inset-middle';
      else if (normalized.includes('inset')) modifier = 'kpmg-divider--inset';
    } else if (normalized.includes('with-text') || (this.text() && rawWidth.toLowerCase().includes('text'))) {
      modifier = 'kpmg-divider--inset-middle-with-text';
      hasText = true;
    } else if (normalized.includes('large')) modifier = 'kpmg-divider--inset-middle-large';
    else if (normalized.includes('medium')) modifier = 'kpmg-divider--inset-middle-medium';
    else if (normalized.includes('small')) modifier = 'kpmg-divider--inset-middle-small';
    else if (normalized === 'inset') modifier = 'kpmg-divider--inset';
    return { modifier, hasText };
  });

  protected readonly hasText = computed(() => this.resolved().hasText);
  protected readonly ariaOrientation = computed(() => this.ariaOrientationOverride() || this.effectiveOrientation());
  protected readonly classes = computed(() => {
    const orientation = this.resolved().hasText ? 'horizontal' : this.effectiveOrientation();
    return `kpmg-divider kpmg-divider--${orientation} kpmg-divider--theme-${this.effectiveTheme()} ${this.resolved().modifier} ${this.className()}`.trim();
  });
}

/** Convenient singular alias (React: `Divider`). */
export const DividerComponent = DividersComponent;

// packages/ui/src/components/Dividers/Dividers.jsx
import React, { forwardRef } from 'react';
import PropTypes from 'prop-types';
import './Dividers.css';

/**
 * KPMG WorkBench Dividers Component
 *
 * Implements all 18 canonical Figma variants:
 * - 2 Orientations: Horizontal, Vertical
 * - 2 Themes: Light, Dark
 * - Inset Configurations:
 *   - Horizontal (12 variants): Full, Inset (16px), Inset middle small (8px),
 *     Inset middle medium (10px), Inset middle large (18px), Inset middle with text ("Subheader")
 *   - Vertical (6 variants): Full, Inset (16px top), Inset middle (16px top & bottom)
 */
export const Dividers = forwardRef(({
  state = 'Horizontal',
  orientation,
  theme = 'Light',
  width = 'Full',
  variant,
  text = 'Subheader',
  className = '',
  style = {},
  role = 'separator',
  'aria-orientation': ariaOrientationProp,
  ...restProps
}, ref) => {
  // Normalize orientation: prop `orientation` takes precedence if passed, otherwise `state`
  const rawOrientation = orientation || state || 'Horizontal';
  const isVertical = rawOrientation.toLowerCase() === 'vertical';
  const effectiveOrientation = isVertical ? 'vertical' : 'horizontal';

  // Normalize theme: Light vs Dark
  const isDark = (theme || 'Light').toLowerCase() === 'dark';
  const effectiveTheme = isDark ? 'dark' : 'light';

  // Normalize width / inset variant
  const rawWidth = variant || width || 'Full';
  const normalizedWidth = rawWidth
    .toLowerCase()
    .replace(/\s+/g, '-');

  // Determine width modifier class
  let widthModifierClass = 'kpmg-divider--full';
  let hasText = false;

  if (isVertical) {
    if (normalizedWidth.includes('inset-middle') || normalizedWidth === 'inset-middle') {
      widthModifierClass = 'kpmg-divider--inset-middle';
    } else if (normalizedWidth.includes('inset')) {
      widthModifierClass = 'kpmg-divider--inset';
    } else {
      widthModifierClass = 'kpmg-divider--full';
    }
  } else {
    if (normalizedWidth.includes('with-text') || (text && rawWidth.toLowerCase().includes('text'))) {
      widthModifierClass = 'kpmg-divider--inset-middle-with-text';
      hasText = true;
    } else if (normalizedWidth.includes('large')) {
      widthModifierClass = 'kpmg-divider--inset-middle-large';
    } else if (normalizedWidth.includes('medium')) {
      widthModifierClass = 'kpmg-divider--inset-middle-medium';
    } else if (normalizedWidth.includes('small')) {
      widthModifierClass = 'kpmg-divider--inset-middle-small';
    } else if (normalizedWidth === 'inset') {
      widthModifierClass = 'kpmg-divider--inset';
    } else {
      widthModifierClass = 'kpmg-divider--full';
    }
  }

  const ariaOrientation = ariaOrientationProp || effectiveOrientation;

  if (hasText) {
    return (
      <div
        ref={ref}
        role={role}
        aria-orientation={ariaOrientation}
        className={`kpmg-divider kpmg-divider--horizontal kpmg-divider--theme-${effectiveTheme} ${widthModifierClass} ${className}`}
        style={style}
        {...restProps}
      >
        <div className="kpmg-divider-line-wrapper">
          <div className="kpmg-divider-line" />
        </div>
        {text && (
          <div className="kpmg-divider-text-container">
            <p className="kpmg-divider-text">{text}</p>
          </div>
        )}
      </div>
    );
  }

  return (
    <div
      ref={ref}
      role={role}
      aria-orientation={ariaOrientation}
      className={`kpmg-divider kpmg-divider--${effectiveOrientation} kpmg-divider--theme-${effectiveTheme} ${widthModifierClass} ${className}`}
      style={style}
      {...restProps}
    >
      <div className="kpmg-divider-line" />
    </div>
  );
});

Dividers.displayName = 'Dividers';

Dividers.propTypes = {
  /** Orientation state: Horizontal or Vertical */
  state: PropTypes.oneOf(['Horizontal', 'Vertical', 'horizontal', 'vertical']),
  /** Alias for state */
  orientation: PropTypes.oneOf(['Horizontal', 'Vertical', 'horizontal', 'vertical']),
  /** Theme styling: Light (subtle neutral line) or Dark (high-contrast line) */
  theme: PropTypes.oneOf(['Light', 'Dark', 'light', 'dark']),
  /** Inset / width configuration matching canonical Figma variants */
  width: PropTypes.oneOf([
    'Full',
    'Inset',
    'Inset middle small',
    'Inset middle medium',
    'Inset middle large',
    'Inset middle with text',
    'Inset middle',
    'full',
    'inset',
    'inset-middle-small',
    'inset-middle-medium',
    'inset-middle-large',
    'inset-middle-with-text',
    'inset-middle',
  ]),
  /** Alias for width */
  variant: PropTypes.string,
  /** Optional subheader text for 'Inset middle with text' variant */
  text: PropTypes.node,
  /** Additional CSS class names */
  className: PropTypes.string,
  /** Inline CSS styles */
  style: PropTypes.object,
  /** ARIA role (default: separator) */
  role: PropTypes.string,
  /** ARIA orientation */
  'aria-orientation': PropTypes.oneOf(['horizontal', 'vertical']),
};

// Convenient singular alias
export const Divider = Dividers;

export default Dividers;
